### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [richardtop/CalendarKit#10]
Hi,
For iOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://bit.ly/2IWvGks)
- [Carthage Tutorial: Getting Started](https://bit.ly/2zes4dN)
- [Making Carthage-compatible Frameworks with Swift](https://bit.ly/2tXUofp)
- [Swift Cross Platform Framework](https://bit.ly/2ysgETA) (section [Configure targets for Carthage](https://bit.ly/2tZUOSt)) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by richardtop** [comment]
Hi, @TofPlay, Carthage support is definitely coming, thanks for this issue. The [DateTools](https://github.com/MatthewYork/DateTools) framework swift version currently does not support Carthage, so I cannot integrate CalendarKit with it.
Once DateTools is out of beta, I will add Carthage support to CalendarKit.
I will keep this issue open.
Or, maybe, you have some other thoughts, how to resolve it? Feel free to discuss here.

**Comment by haithngn** [comment]
@richardtop,
Could we replace DateTools by [SwiftDate](https://github.com/malcommac/SwiftDate) then make CalendarKit completely support Carthage method ?

**Comment by richardtop** [comment]
@haithngn Yes, that's possible. Feel free to submit pull request, if you would like to replace `DateTools` with `SwiftDate`.

**Comment by haithngn** [comment]
I have tried migrate to SwiftDate but currently CalendarKit has tight depend with DateTools's models then we have to solve that problem first.
as you know DateTools is now preparing to support Carthage so I think we have two choices:
- wait for DateTools support Carthage.
- create any CalendarKit Model class then migrate to any Date vendor frameworks.
What do you think ?

**Comment by richardtop** [comment]
1. Yes, CK has a tight dependency, it was built this way (without plans to replace Neon & DateTools)
2. Waiting for DT to support Carthage is  a status quo
3. Feel free to submit a pull request if you are willing to implement this change.

Otherwise, I'd recommend you using different tool to integrate CK with your project, e.g. `CocoaPods`, Git Submodules or just by copying the source.

**Comment by tschmitz** [comment]
Any chance that CalendarKit will support Carthage in the near future?

**Comment by richardtop** [comment]
@tschmitz yes, it will, please take a look at the prerequisites to make that change possible.

**Comment by richardtop** [comment]
Carthage support is not planned anymore, I suggest using swift package manager instead.
