### ISSUE TITLE
Can we get WeekView along with DayView?

### ISSUE THREAD

**Issue by Naveentp** [richardtop/CalendarKit#100]
Great Library. The way you are responding for every issue is too good. I am looking for WeekView along with this Dayview. I don't want to go for another library for WeekView. Is there any chance of implementing it?

**Comment by richardtop** [comment]
Hi, thank you for the warm words.
At first, I'd like to clarify, that this feature has already been asked in #62.
Currently, there is no plans on implementing these views, as there are many other good libraries to pick from. For example [CVCalendar](https://github.com/CVCalendar/CVCalendar) or [JTCalendar](https://github.com/jonathantribouharet/JTCalendar) and they are not the only ones.

So, I'd recommend to use another library for the month view together with CalendarKit. It's better to have a two good libraries than one bad.

However, at some time in the future I see the reasons to implement both MonthView and YearView in one library, so I mark your issue as a feature request.

If you have any troubles integrating CalendarKit with another library, feel free to ask here.

**Comment by richardtop** [comment]
Closed in favor of #22
