### ISSUE TITLE
I am stuck with creating events from server and even example dates and time also

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [richardtop/CalendarKit#101]
@richardtop  Please help me, i was struggling to create event  with from last 2 week.  how to create events with date & time. help me

**Comment by richardtop** [comment]
Hi, creating events is simple. Here are the steps:
1. Get information from the source (it can be a server, database, or a random generator)
2. Create an array of `Event` objects and pass it in the `DayViewDataSource` method

I wouldn't go into details on the 1st part, but will elaborate on 2nd.
The `Event` object contains all the information required to display a single event.

The steps to configure an event as follows:

At first, it needs to be created
```Swift
      let event = Event()
```
Then, a [TimePeriod](https://github.com/MatthewYork/DateTools) must be added.
The TimePeriod defines the start, the end and the duration of the event.
```Swift
      event.datePeriod = TimePeriod(beginning: model.beginning, end: model.start)
```

The text could be added by setting either `text` or `attributedText` properties:
```Swift
      event.text = "Meeting at Central Railway Station \n 12:00 - 15:00"
```
Events related to different categories (Work or Home) could be coloured differently:
```Swift
      event.color = .red
```

I hope, I answered your question.

**Comment by IOSDeveloperProgrammer** [comment]
@richardtop Sorry, Still stuck with creating 'TImePeriod' 
` event.datePeriod = TimePeriod(beginning: model.beginning, end: model.start)`

This my JSON Response, Please check 
`"schedule": [
                {
                    "caldate": "2017-11-07",
                    "subname": "General Knowledge",
                    "frmtm": "10:15:00",
                    "totm": "11:00:00"
                },
                {
                    "caldate": "2017-11-07",
                    "subname": "Mathematics",
                    "frmtm": "11:00:00",
                    "totm": "11:45:00"
                },
                {
                    "caldate": "2017-11-07",
                    "subname": "Hindi",
                    "frmtm": "8:00:00",
                    "totm": "8:45:00"
                },]`
How can i create time period and add on calendar.  I need to display  class time schedule on day-day. Please help  I'm stuck.

**Comment by nizzam** [comment]
@richardtop what is the calendar format ?

**Comment by richardtop** [comment]
The API no longer requires its clients to provide `datePeriod`. Only two properties are needed: `startDate` and `endDate`.
