### ISSUE TITLE
how to select user specific date when  executed initially 

### ISSUE THREAD

**Issue by maheshiosdeveloper** [richardtop/CalendarKit#105]

**Comment by richardtop** [comment]
You can select a specific date by invoking a method `move(to date: Date)` on `DayViewState`:
`dayView.state.move(to: #SPECIFIC_DATE)`

**Comment by maheshiosdeveloper** [comment]
By using dayView.state.move(to: #SPECIFIC_DATE) the date which i set is in the perticular weak then it is showing the date which i set otherwise its showing the current date

**Comment by eastsss** [comment]
the problem is that if you're trying to select a date which is not in the current week, it won't work

**Comment by richardtop** [comment]
@SachinTanpure did you call `dayView.state.move(to: #SPECIFIC_DATE)` before or after the `dataSource` has been set?

This method should be called with the `dataSource` attached, so the _CalendarKit_ can fetch new events.

If the bug remains, please, open a new issue with sample code to reproduce it.
