### ISSUE TITLE
Help calendar empty: Trying to add School Class lessons to calendar

### ISSUE THREAD

**Issue by fustav** [richardtop/CalendarKit#108]
Hello, I am having problems with adding calendar school class lessons.

I retrieve data from the server for each Subject (i.e. Bass class, guitar, drum, musical theory class, etc.)
For each class I have an object array of array with subject , class room ,  id, and an array of String of dayLessons formatted as dd-MM-yyyy

dayLessons = [dayLesson1, dayLesson2, ..., dayLessonN] = ["dd-MM-yyyy" ... ]

I first tried to show on calendar all lessons for each day and I can get data correctly by adding for each class the start time and his duration which I got from Server and converting in Int:

`var date = date.add(TimeChunk.dateComponents(minutes: Int(startMinutes!)!, hours: Int(startHour!)!))
`
`let datePeriod = TimePeriod(beginning: date,chunk: TimeChunk.dateComponents(minutes: duration))`

![img_0339](https://user-images.githubusercontent.com/5604935/31715264-5e60abd6-b403-11e7-96de-53d9d0348732.PNG)

But of course I need to sort the calendar in order to show the specific lesson on the specific day, when I try to add to TimeChunck this is the result

` date = date.add(TimeChunk.dateComponents(days: Int(day!)!, months: Int(month!)!, years: Int(year!)!))`

![img_2335862386e7-1](https://user-images.githubusercontent.com/5604935/31715373-dbc5d524-b403-11e7-8923-d995386b2d29.jpeg)

Any help please???
Thank you in advance

**Comment by richardtop** [comment]
Hi, could you post an example server responses here?

**Comment by IOSDeveloperProgrammer** [comment]
@richardtop Thanks! I am having same problem for adding lesson. This is my server response 
`{
    "status": 200,
    "data": [ {
            "caldate": "02-Oct-2017",
            "schedule": [
                {
                    "caldate": "2017-10-02",
                    "subname": "Hindi",
                    "frmtm": "14:00",
                    "totm": "14:30",
                    "rsttyp": "subject"
                },
                {
                    "caldate": "2017-10-02",
                    "subname": "Mathematics",
                    "frmtm": "14:30",
                    "totm": "15:00",
                    "rsttyp": "subject"
                },
                {
                    "caldate": "2017-10-02",
                    "subname": "Lunch",
                    "frmtm": "15:00",
                    "totm": "15:30",
                    "rsttyp": "period"
                }
            ],
            "rsttyp": "period"
        },
        {
            "caldate": "02-Oct-2017",
            "schedule": [
                {
                    "caldate": "2017-10-02",
                    "subname": "Hindi",
                    "frmtm": "14:00",
                    "totm": "14:30",
                    "rsttyp": "subject"
                },
                {
                    "caldate": "2017-10-02",
                    "subname": "Mathematics",
                    "frmtm": "14:30",
                    "totm": "15:00",
                    "rsttyp": "subject"
                },
  ],
            "rsttyp": "holiday"
        }
    ]
}`
 Please guide me

**Comment by fustav** [comment]
@IOSDeveloperProgrammer I could find out a solution but the calendar kit run execution is too slow!
@richardtop 
I retrieve my Server data in background when the user is logging-in, I save data into an array of custom struct object "DayLessons"  (from the server it is calle GiorniSpot)

This is the server response:
`[{"Anno":"2017","Articolo":"TEOARM03","Aula":"A13","Corso":"TEORIA: Teoria e Armonia","DataFine":"28-05-2018","DataInizio":"09-10-2017","DescrClasse":"Teoria e Armonia III - 3^","Docente":"Teacher Name1","GiorniSpot":[{"DataLezione":"09-10-2017"},{"DataLezione":"16-10-2017"},{"DataLezione":"23-10-2017"},{"DataLezione":"30-10-2017"},{"DataLezione":"06-11-2017"},{"DataLezione":"13-11-2017"},{"DataLezione":"27-11-2017"},{"DataLezione":"04-12-2017"},{"DataLezione":"11-12-2017"},{"DataLezione":"18-12-2017"},{"DataLezione":"08-01-2018"},{"DataLezione":"15-01-2018"},{"DataLezione":"22-01-2018"},{"DataLezione":"29-01-2018"},{"DataLezione":"05-02-2018"},{"DataLezione":"12-02-2018"},{"DataLezione":"19-02-2018"},{"DataLezione":"26-02-2018"},{"DataLezione":"05-03-2018"},{"DataLezione":"12-03-2018"},{"DataLezione":"19-03-2018"},{"DataLezione":"26-03-2018"},{"DataLezione":"09-04-2018"},{"DataLezione":"16-04-2018"},{"DataLezione":"23-04-2018"},{"DataLezione":"14-05-2018"},{"DataLezione":"21-05-2018"},{"DataLezione":"28-05-2018"}],"Giorno":"Lun","IdAllievo":"4429","IdClasse":"13136","IdCorso":"1539","IdDocente":"0864","Orario":" (11:00-12:00)","TipoOrario":"Spot"},{"Anno":"2017","Articolo":"EARTRA03","Aula":"A14","Corso":"EAR TRAINING 1^ - 2^ - 3^","DataFine":"28-05-2018","DataInizio":"05-02-2018","DescrClasse":"Ear Training course III - 3^","Docente":"Teacher Name2","GiorniSpot":[{"DataLezione":"05-02-2018"},{"DataLezione":"12-02-2018"},{"DataLezione":"19-02-2018"},{"DataLezione":"26-02-2018"},{"DataLezione":"05-03-2018"},{"DataLezione":"12-03-2018"},{"DataLezione":"19-03-2018"},{"DataLezione":"26-03-2018"},{"DataLezione":"09-04-2018"},{"DataLezione":"16-04-2018"},{"DataLezione":"23-04-2018"},{"DataLezione":"14-05-2018"} etc etc...`


This is what I did, please help me with speeding it up (it takes a lot to load events for each day):


` override func eventsForDate(_ date: Date) -> [EventDescriptor] {
   
    var events = [Event]()


    for i in MyClassesArray {  
         for j in i.giorniSpot! {       // giorniSpot = dayLessonsArray, day lessons for each specific class
              let event = Event()
              var date = Date()
            
           //  //Server gave me data as strings with empty spaces and issues, i just take what i need
            let startHour = i.orario?[2...3] 
            let startMinutes = i.orario?[5...6]

        
            let userCalendar = Calendar.current
            let dateFormatter = DateFormatter.init()
        
            dateFormatter.calendar = userCalendar
            dateFormatter.dateFormat = "dd/MM/yyyy"
        
            let dataLezione = j.dataLezione    //i.e. today is 24/10/2017 
            date = dateFormatter.date(from: dataLezione!)!  //now I have the day lessons 
      
     // lessons start always at the same time for each class
     date = date.add(TimeChunk.dateComponents(minutes: Int(startMinutes!)!, hours: Int(startHour!)!))


        
    
        //TO GET DURATION OF EACH LESSON from string
        let rangeStart = i.orario?[2...6] 
        let trimmedStringIndex = rangeStart?.replacingOccurrences(of: "\\D", with: "", options: .regularExpression)
        
        let rangeFinish = i.orario?[8...12] //orario fine
        let trimmedStringFinish = rangeFinish?.replacingOccurrences(of: "\\D", with: "", options: .regularExpression)
        
        let trimmedStringIndexInt = Int(trimmedStringIndex!)
        let trimmedStringFinishInt = Int(trimmedStringFinish!)
        
        let duration = Int(((trimmedStringFinishInt! - trimmedStringIndexInt!)/100)*60)
 
        let datePeriod = TimePeriod(beginning: date,chunk: TimeChunk.dateComponents(minutes: duration))
        
        
            event.datePeriod = datePeriod
            
            var info = i.descrizione //"DescrClasse" from the Server gave me the Full Classname 
            let orario = i.orario
            let aula = i.aula
         
            info = info! + "\n " + orario! + "  Aula: " + aula!
        
            event.text = info!
      
      
            event.color = self.colors[Int(arc4random_uniform(UInt32(self.colors.count)))]
            events.append(event)

            //let nextOffset = Int(arc4random_uniform(250) + 40)
            //date = date.add(TimeChunk.dateComponents(minutes: nextOffset))
            event.userInfo = String(describing: i)
            } // end for j
        } // end for i
    

       return events
     

  }
`

**Comment by IOSDeveloperProgrammer** [comment]
@fustav  thanks, I will try let you know.

**Comment by IOSDeveloperProgrammer** [comment]
@fustav Can you please  Once Check this issue #101
