### ISSUE TITLE
how to flip the Time Labels from left to right 

### ISSUE THREAD

**Issue by NadeemHakim** [richardtop/CalendarKit#109]
Timeline below 
With Color to be changed 

![timeline](https://user-images.githubusercontent.com/5569017/31996992-7b87fe9c-b99b-11e7-8ecc-0db7deb2c91f.png)

**Comment by richardtop** [comment]
Currently there are no such functionality in the library.

**Comment by NadeemHakim** [comment]
Noted

**Comment by richardtop** [comment]
#161
