### ISSUE TITLE
Modify size of calendar

### ISSUE THREAD

**Issue by christophercarlsson** [richardtop/CalendarKit#112]
Hi,
I want to add a view of custom controls specific for my app at the bottom om the view controller. I've added my view and brought it to the front, but it covers part of the timeline and I don't seem to be able to align the timeline above my view so that I can see the whole thing.
How do I proceed?

Best regards

**Comment by richardtop** [comment]
Hi,
it is possible in the current implementation.

These steps will help you achieve the desired result:
1. Create a subclass of the UIViewController,
in the subclass:
2. Create an instance of the DayView
3. Add DayView to the main view of the ViewController as a subview
4. Resize the DayView to the desired dimensions.

Implement all the `DayViewController` methods, for example, by copying them.

So, the idea is to create a new ViewController and use DayView there.
