### ISSUE TITLE
Date scroll bar not matching the date label display

### ISSUE THREAD

**Issue by acshih** [richardtop/CalendarKit#114]
I've been having issues with using JT Apple Calendar to select a date. The label will display the proper date, but the date selector above it, does not reflect the date that the label shows.

Is there an easy way to fix this? I've been told that it may be a bug.

The date scroll bar seems to take the current date, instead of the date that's been selected, say January 17th instead of showing November 19, 2017.

![screen shot 2017-11-19 at 9 31 26 pm](https://user-images.githubusercontent.com/17653416/33003689-1dcad93e-cd71-11e7-84be-ad4592eb8886.png)

**Comment by richardtop** [comment]
[Relevant StackOverflow discussion](https://stackoverflow.com/questions/47495195/calendarkit-issue-with-the-date-scroll-bar-swift/47605452#47605452)
