### ISSUE TITLE
Color on timeIndicators timelabel

### ISSUE THREAD

**Issue by jSunnari** [richardtop/CalendarKit#115]
Hi

Is it possible to change to color of the timelabel on the timeindicator showing the current time?
Alternatively, is there any way to hide it?

**Comment by jSunnari** [comment]
I just figured out that `timeline.timeIndicator.font = UIFont.systemFont(ofSize: 0)`is a way to hide the label.

**Comment by richardtop** [comment]
Alternatively, you could use `isHidden` property of the _UIView_ to achieve the same result.
