### ISSUE TITLE
How do I select a specific time?

### ISSUE THREAD

**Issue by Bodgar** [richardtop/CalendarKit#116]
Good day, what I want to do is something similar to what you do when you click on the event, but I just want to click on a specific time to create an event at that time. How can I do it?

**Comment by richardtop** [comment]
Hi, you can use the delegate method:
```Swift
  func dayViewDidLongPressTimelineAtHour(_ hour: Int)
```

Or, modify library, if you want to handle _Tap_ events instead of _LongPress_
