### ISSUE TITLE
How to add new event?

### ISSUE THREAD

**Issue by Bodgar** [richardtop/CalendarKit#117]
Good morning, I am trying once that you click on a specific time, an alert can appear and you can place the event. How can I update the timeline so that the event is already placed? Thanks!!

**Comment by richardtop** [comment]
In order to add a new event, you should do the following steps:
1. Update your _EventDataSource_ by adding/removing events.
2. Call _reloadData()_ method on _DayView_
The timeline should reflect all the changes.
