### ISSUE TITLE
What day CalendarView is showing?

### ISSUE THREAD

**Issue by IronMaltes** [richardtop/CalendarKit#119]
Hi Richard, first of all thanks for creating such an amazing good looking calendar.
I have a question maybe too simple but I can not find the correct way to determine what day I'm in. 

I've seen the fuction eventsForDate is called several times, also I see that I can monitor func dayView(dayView: DayView, willMoveTo date: Date)... but is there a property o methode to determine what day the view is showing?

Thanks,
Alex.

**Comment by richardtop** [comment]
Hi @IronMaltes, and thank you, I'm glad that you liked the library.

To get the current date, simply get the `selectedDate` property of _DayViewState_:
```Swift
let currentDate = dayView.state.selectedDate
```

**Comment by IronMaltes** [comment]
Thanks, so easy, I coudn't find it ;-)
