### ISSUE TITLE
Same name as MBCalendarKit

### ISSUE THREAD

**Issue by MosheBerman** [richardtop/CalendarKit#12]
Hey,

This looks like a great library! 

I made a [similar library](https://github.com/MosheBerman/MBCalendarKit) with a very similar name a few years ago. If/when I Port to Swift, I'd want to drop the prefix, and as it stands this becomes a conflict. 

Any chance you would consider renaming (or at least prefixing) this one?

Thanks!

**Comment by richardtop** [comment]
Hi, 
I see your point, however, I doubt whether it is technically possible. This repo has been already pushed to the trunk, so what we could do is to `deprecate this repo in favor of`, which makes no sense, as the `CalendarKit` will still exist.
Here is the SO question:
http://stackoverflow.com/questions/28789807/how-to-rename-a-cocoapod
Another option is to completely remove this library via pull request and then re-push under a new name. But what's the point, if there is [a third library with similar name](https://github.com/Mozharovsky/CVCalendarKit).

This project started as an experiment to create a set of views to make own customized calendar, or to make some other UI elements based on it. Hence the name, CalendarKit.

I think, it's OK to return to this question when you're going to publish your implementation, but I can't see the problem if names are unique. What do you think about this?

**Comment by MosheBerman** [comment]
You raise a good point about the difficulty with renaming the CocoaPod, so let's leave it as is. I'll just have to be creative in the name of my new one. ;)

Thanks!
