### ISSUE TITLE
How to translate UIGestureRecognizer.location to a timeline hour?

### ISSUE THREAD

**Issue by IronMaltes** [richardtop/CalendarKit#121]
Hi Richard, hope your doing well

Is there any way to implement something that can translate the position or location of the eventViewDidLongPress in @objc func longPress() (in EventView.swift) into a timeline hour? in such a way the dragging of an event could be implemented.

Thanks

**Comment by richardtop** [comment]
Hi @IronMaltes,
sorry for late answer.
Currently there is no support for event dragging, however, it would be a great feature for the library.

**Comment by richardtop** [comment]
Implemented in the latest release of the CalendarKit

**Comment by IronMaltes** [comment]
Thanks! I'll give it a try to see what can be implemented on top of that.
Any documentation on how to use it?

Great job man!
