### ISSUE TITLE
View for notification

### ISSUE THREAD

**Issue by grosch** [richardtop/CalendarKit#122]
This looks like an awesome library.  Is there a way to customize the view so it just shows the time around a specific timeframe?   I'd like to use this in a custom UI for a rich push notification but obviously I don't want to show the whole day, just a couple hours before and after the event that's pushed to the user.

**Comment by richardtop** [comment]
Hi @grosch,

_CalendarKit_ was meant to be a set of separate modules, so you could use it to create your own UI components.

For your task, I'd recommend using just [TimelineView](https://github.com/richardtop/CalendarKit/blob/master/Source/Timeline/TimelineView.swift), it should serve the purpose perfectly.

If you'd like to have a higher-level abstraction over _TimelineView_, you may wrap it into [TimelineContainer](https://github.com/richardtop/CalendarKit/blob/master/Source/Timeline/TimelineContainer.swift) to support scrolling to specific hour or the first event.

**Comment by grosch** [comment]
Thanks, @richardtop.  Could you give a bit more of a specific example please?  I'm looking at TimeLineView and none of the stuff in there is public so I'm not sure how to use this by itself.

**Comment by richardtop** [comment]
At first, I recommend you taking a look at the "parent" view, i.e. [TimelinePagerView](https://github.com/richardtop/CalendarKit/blob/master/Source/Timeline/TimelinePagerView.swift). The method important for us is _updateTimeline_:
```Swift
  func updateTimeline(_ timeline: TimelineView) {
    guard let dataSource = dataSource else {return}
    let date = timeline.date.dateOnly()
    let events = dataSource.eventsForDate(date)
    let day = TimePeriod(beginning: date,
                         chunk: TimeChunk.dateComponents(days: 1))
    let validEvents = events.filter{$0.datePeriod.overlaps(with: day)}
    timeline.eventDescriptors = validEvents
  }
```
The last line shows, how  the information in form of _[EventDescriptor]_ is passed to the _Timeline_.

Also, you'll need to position your view in the parent view, i.e. set it's frame's `y` to some arbitrary number:
```Swift
let hourToScroll = 18 // Scroll to 18:00
let fullHeight = timeline.fullHeight
let yOffset = fullHeight * hourToScroll/24
timeline.frame = CGrect(x: 0, y: yOffset, width: ...., height: ...)
```

**Comment by grosch** [comment]
Thanks.  Still not there though.  Everything seems to be internal variables.  I can put a `TimelinePagerView` on my screen and it draws fine.  However, `updateTimeline` wants to use the internal timeline variable to get the internal `date` variable so I can't actually set what the date is that I'm looking at.

**Comment by grosch** [comment]
Is there any chance you can just provide an example view controller that displays a day view set to a specific date with some events?

**Comment by richardtop** [comment]
I'll send you an example in a moment

**Comment by richardtop** [comment]
@grosch I've added example in #126 
It looks like this:
![image](https://user-images.githubusercontent.com/8013017/34363936-5cb62c68-ea89-11e7-894a-79963cf46956.png)

You may want to tweak the library to meet specific requirements. Feel free to change it and open a pull request.

**Comment by grosch** [comment]
Thanks!  Please remember to update the cocoapod as well.  It's still pulling 0.2.1

**Comment by richardtop** [comment]
Done. Feel free to close this issue, if you don't have other questions related to the Notification view.

**Comment by grosch** [comment]
Thanks much.  I've almost got this working now.  Might need to make a couple more things public, like is24hClock.  I'll open a new item on what I'm finding though.
