### ISSUE TITLE
Timeline not scrolling properly

### ISSUE THREAD

**Issue by thederekkaplan** [richardtop/CalendarKit#123]
I am creating a custom header as part of my view controller, so I have removed the header from the day view I have in my view controller. However, when I scroll to the bottom of the timeline, it will not let me scroll past 9 PM.

<img width="598" alt="screen shot 2017-12-24 at 11 00 23 am" src="https://user-images.githubusercontent.com/34196535/34328310-b0576b9e-e899-11e7-86f6-f812cb3593b8.png">

The image I have attached shows how far it will let me scroll. If I try to scroll past it, it acts as if I am trying to scroll beyond the edge and simply pops back to the pictured position once I let go.

**Comment by richardtop** [comment]
Hi @thederekkaplan,

In order to better understand this issue, I'd like to ask, how are you adding a custom header to the _DayView_?

Would be good, if you could provide some code snippet, so I will be able to reproduce and investigate this issue.

**Comment by thederekkaplan** [comment]
I am setting `dayView.isHeaderViewVisible = false` for the dayView and using my own views in my view controller.

**Comment by richardtop** [comment]
@thederekkaplan could you post a code sample that reproduces this bug? I guess, the root cause of the problem is that the header's height is higher than CK's standard. Therefore, it has to be changed in case of custom header. I need to look in detail, how are you using CK to be able to help.
