### ISSUE TITLE
Container scrolling too far.

### ISSUE THREAD

**Issue by grosch** [richardtop/CalendarKit#127]
### Issue Description
The scroll view seems to be going too far when I point at 7pm to scroll to.

##### Code I'm using with CalendarKit
```Swift
let timeline = TimelineView()
timeline.date = startDate
timeline.frame.size.height = timeline.fullHeight

let container = TimelineContainer(timeline)
container.contentSize = timeline.frame.size
container.translatesAutoresizingMaskIntoConstraints = false
container.addSubview(timeline)

view.addSubview(container)
NSLayoutConstraint.activate([
    container.topAnchor.constraint(equalTo: view.topAnchor),
    container.bottomAnchor.constraint(equalTo: view.bottomAnchor),
    container.leadingAnchor.constraint(equalTo: view.leadingAnchor),
    container.trailingAnchor.constraint(equalTo: view.trailingAnchor)
])

timeline.eventDescriptors = ...

container.scrollTo(hour24: Float(startDate.hour))
```

Notice the green background view that's showing through.

![image](https://user-images.githubusercontent.com/315966/34366162-ee95c22a-ea4c-11e7-8484-898ff49f4247.png)

**Comment by richardtop** [comment]
Currently, CalendarKit does not take "overscroll" possibility into account. You have to implement it either manually, or apply a patch to _TimelineContainer_

**Comment by grosch** [comment]
Awesome!  @richardtop please remember to update the POD to include these fixes.

**Comment by richardtop** [comment]
@grosch I'll update pod soon, but if you want to receive all the newest changes, you can add link to this repository in the podfile.

**Comment by grosch** [comment]
@richardtop ETA on when you'll fix the POD?
