### ISSUE TITLE
Crash - When navigating calendar by week in DayHeaderView [Because of year change?]

### ISSUE THREAD

**Issue by harshag** [richardtop/CalendarKit#128]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
CalendarKit is crashing on new year. The DayHeaderView is not getting set correctly and when we navigate by swiping left or right, the app crashes.

I downloaded the latest code from repo and can see it happening in the demo app. I have attached screenshots of where the app is crashing along with demo app screenshot.
Notice the DayHeaderView, its not correct.
<img width="825" alt="crash-code" src="https://user-images.githubusercontent.com/1763746/34467971-869e2b4e-ef24-11e7-9e6f-990a2759a84b.png">
![demoapp-screen](https://user-images.githubusercontent.com/1763746/34467972-86ceeca2-ef24-11e7-8001-e5ccda41433b.png)

**Comment by richardtop** [comment]
Thank you for reporting this issue, it was quite obscure. Now it's fixed.
