### ISSUE TITLE
Got Swift Compiler Error in CalendarKit

### ISSUE THREAD

**Issue by opw0011** [richardtop/CalendarKit#13]
I have followed the installation guide, but still failed to integrate your library to my existing project.
I retried a few time, but still getting the same errors like this:
![a](https://cloud.githubusercontent.com/assets/10897048/22656085/28b0a7fa-eccd-11e6-9e51-398c51c1f098.png)

I noticed that recently DateTools have released the latest swift update.
It changed from `pod 'DateTools'` to 'pod 'DateToolsSwift'`
Not sure if it is a issue...
I would be graceful if you could help me to solve this. Thanks.

**Comment by richardtop** [comment]
@opw0011 Thanks for pointing this out. `DateTools` has been updated and Swift counterpart pushed to trunk. I've updated `CalendarKit` to use that new version and changed readme. Could you try again? And do not forget to remove any reference to `DateTools` from your `podfile`, as now it should be fetched automatically.

**Comment by opw0011** [comment]
Works like a charm 👍
