### ISSUE TITLE
New Year - Off by one error for the first week.

### ISSUE THREAD

**Issue by jameswwwebster** [richardtop/CalendarKit#130]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

At the start of the year, Week 1 appears to show the dates for a year +1 in the future. 
e.g. as we've just entered 2018, the calendar is showing the dates for 2019 for week one

Note that 4th Jan 2018 is a Thursday, but here it is displayed as a Friday.

![screen shot 2018-01-04 at 08 58 17](https://user-images.githubusercontent.com/17748510/34559623-745ece62-f13a-11e7-9a8f-92f08b96e7fd.png)

**Comment by Jonyleeson** [comment]
I also had the same bug (or at least I think it's the same one), what ended up working for me was editing DayHeaderView.swift, line 66, replacing:

```
  func beginningOfWeek(_ date: Date) -> Date {
    return calendar.date(from: DateComponents(calendar: calendar,
                                              weekday: calendar.firstWeekday,
                                              weekOfYear: date.weekOfYear,
                                              yearForWeekOfYear: date.yearForWeekOfYear))!
  }
```

with   

```
  func beginningOfWeek(_ date: Date) -> Date {
    return calendar.date(from: calendar.dateComponents([ .yearForWeekOfYear, .weekOfYear ], from: date))!
  }
```

worked for me

**Comment by richardtop** [comment]
Hi @jameswwwebster and @Jonyleeson,
Please take a look at #128 and #129.
Are you sure, you're using the latest version?

**Comment by jameswwwebster** [comment]
Oh possibly not! Sorry!

I have updated in my most recent branch, but may have been running an old version of my code

________________________________

**Comment by Jonyleeson** [comment]
Welp me neither

**Comment by richardtop** [comment]
@jameswwwebster , @Jonyleeson could you check which version are you using in your `podfile.lock`?

I'll be able to debug it this weekend.

**Comment by Jonyleeson** [comment]
Oh no for sure I didn't have the latest version, sorry if I wasn't clear, I was at 0.2.1

**Comment by richardtop** [comment]
@Jonyleeson then it's a good idea to test, whether CocoaPods fetches the latest version with the `pod update`. There was an issue related to the problem #110

**Comment by richardtop** [comment]
@Jonyleeson, @jameswwwebster do you still have this issue unresolved?
If everything works fine, I'll close it.

**Comment by jameswwwebster** [comment]
I haven’t been specifically looking out for it, but I haven’t seen it since thanks Richard

________________________________

**Comment by richardtop** [comment]
@jameswwwebster OK, closing it for now and consider resolved.
