### ISSUE TITLE
Toolbar will background  color change to Gray 

### ISSUE THREAD

**Issue by WingCH** [richardtop/CalendarKit#142]
### New Issue Checklist

- [0.3.0] Use the latest version of CalendarKit
- [Y] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [Y] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Toolbar will background  color change to Gray 

![img_9396](https://user-images.githubusercontent.com/19588517/36637889-c65128aa-1a20-11e8-853b-9664298d7240.png)

**Comment by richardtop** [comment]
Hi, @WingCH, could you please share your code for this screen, so I could reproduce it in my environment?

**Comment by WingCH** [comment]
> Storyboard
<img width="1006" alt="2018-02-26 at 2 57 pm" src="https://user-images.githubusercontent.com/19588517/36657027-d8a17a24-1b05-11e8-93ca-f6ea59044c60.png">

[RoomDetailViewController.swift.zip](https://github.com/richardtop/CalendarKit/files/1757528/RoomDetailViewController.swift.zip)

**Comment by richardtop** [comment]
Unfortunately, I can't reproduce the issue using that file.
Please, create a new project, install `CalendarKit` and do the minimal number of tweaks and adjustments needed to showcase this issue.

Alternatively, you could set the [translucent](https://developer.apple.com/documentation/uikit/uitabbar/1623458-translucent) property of the `UITabBar` to _false_ and the issue should be resolved.

```Swift
let tabBar = // Get the UITabBar from UITabBarViewController
tabBar.translucent = false
```
