### ISSUE TITLE
Calendar by week

### ISSUE THREAD

**Issue by djxmax** [richardtop/CalendarKit#148]
Hello, your library is really amazing. It's almost all i want for my app. 👍 
But I have a question (I search in issue but I haven't find the answer) : calendar is day by day, is there a solution to make it week by week ? Something like that : 
<img width="372" alt="capture d ecran 2018-04-11 a 10 25 58" src="https://user-images.githubusercontent.com/7045905/38605525-db9457ca-3d73-11e8-9332-759a01343d25.png">
Thanks for your future reply.

**Comment by Nikoloutsos** [comment]
@djxmax  Sorry for asking but I am interested in building something like the picture you sent.
Have you find anything? Can you share it with us??

**Comment by richardtop** [comment]
Closed in favor of #22
