### ISSUE TITLE
Current version won't build

### ISSUE THREAD

**Issue by grosch** [richardtop/CalendarKit#151]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

Unable to compile my project after adding your pod.  I'm getting errors from DateToolsSwift that you're still dependent on.

**Comment by richardtop** [comment]
Hi @grosch,
could you post the contents of your `Podfile.lock` here, please?

**Comment by grosch** [comment]
I had to force CocoaPods itself to update as it wasn't getting your newest version.

**Comment by richardtop** [comment]
@grosch Could you please specify, how you achieved it?

**Comment by grosch** [comment]
Running a 'pod install' even with the entire Pods directory gone wasn't doing anything so I ran a 'pod outdated' and that forced it to update my local repository and then a 'pod update' fixed it.

**Comment by richardtop** [comment]
`pod update` should suffice most of the time.

I regularly push new updates to the library, so it's always good to be on the latest version.
