### ISSUE TITLE
'datePeriod' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by phaninderkumar** [richardtop/CalendarKit#152]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Not able to build my project due to the error **'datePeriod' is inaccessible due to 'internal' protection level**. It worked fine before.

##### Code I'm using with CalendarKit

```Swift

let event = Event()
event.datePeriod = TimePeriod.init(beginning: startDate, end: endDate)
event.userInfo = ["index": index, "section": sectionIndex]
var info = [agenda.title!]
info.append("\(event.datePeriod.beginning!.format(with: "HH:mm")) - \(event.datePeriod.end!.format(with: "HH:mm"))")

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Hi @phaninderkumar,

The latest version of the CalendarKit doesn't require `datePeriod`.
Instead, you need to specify the start and the end dates.

For example:
```Swift
      let event = Event()
      // Specify StartDate and EndDate
      event.startDate = model.startDate
      event.endDate = model.endDate
```

You can read more in [Readme](https://github.com/richardtop/CalendarKit#usage)

**Comment by grosch** [comment]
@richardtop Thank you for making this change.  So much nicer!

**Comment by phaninderkumar** [comment]
Thanks @richardtop.

**Comment by richardtop** [comment]
@phaninderkumar I'm closing this issue, as I guess it has been resolved.
Feel free to reopen, if you have some more questions.
