### ISSUE TITLE
TimelineView events

### ISSUE THREAD

**Issue by grosch** [richardtop/CalendarKit#153]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

In previous conversations you helped me use the TimelineView for a push notification UI by directly setting the `eventDescriptors` of the `TimelineView` but in the newest versions that property no longer exists, and I'm not seeing an obvious replacement.  Can you help me understand how to accomplish this now?

##### Code I'm using with CalendarKit

This is what I was previously doing

```Swift
    let timeline = TimelineView()

    let predicate = eventStore.predicateForEvents(withStart: startDate, end: endDate, calendars: nil)
    timeline.eventDescriptors = eventStore.events(matching: predicate).map { event in
      let calendarKitEvent = Event()
      calendarKitEvent.startDate = event.startDate
      calendarKitEvent.endDate = event.endDate
      calendarKitEvent.text = event.title
      calendarKitEvent.color = UIColor(cgColor: event.calendar.cgColor)
      
      return calendarKitEvent
    }
```

#### Result I am trying to achieve

Just trying to show a small chunk of the calendar in a custom UI for push notification.

**Comment by richardtop** [comment]
Please take a look at the code in  [TimelinePagerView](https://github.com/richardtop/CalendarKit/blob/master/Source/Timeline/TimelinePagerView.swift#L109) and configure your `timeline` accordingly.

You'll need to pass instances of layout attributes instead of events.

**Comment by richardtop** [comment]
@grosch here is an example from the sample code:
```Swift
  override func viewDidLoad() {
    super.viewDidLoad()
    view.backgroundColor = .lightGray
    view.addSubview(timelineContainer)
    timelineContainer.timeline.date = Date()
    
    let date = Date()
    let event = Event()
    let duration = 80
    let datePeriod = TimePeriod(beginning: date,
                                chunk: TimeChunk.dateComponents(minutes: duration))
    
    event.startDate = datePeriod.beginning!
    event.endDate = datePeriod.end!

    var info = ["Compliance report"]
    info.append("\(datePeriod.beginning!.format(with: "dd.MM"))")
    info.append("\(datePeriod.beginning!.format(with: "HH:mm")) - \(datePeriod.end!.format(with: "HH:mm"))")
    event.text = info.reduce("", {$0 + $1 + "\n"})
    event.color = .red
    timelineContainer.timeline.layoutAttributes = [EventLayoutAttributes(event)]
    timelineContainer.scrollTo(hour24: 20)
  }

```

More in [ExampleNotificationController](https://github.com/richardtop/CalendarKit/blob/master/CalendarKitDemo/CalendarKitDemo/ExampleNotificationController.swift)

Closing this issue, as it should be resolved by now. Feel free to reopen, if you have any more questions.

**Comment by grosch** [comment]
I'm sorry this has taken me so long to respond.  I've been horribly sick for a while and I'm finally getting back to things.   I put a TimelineView into the storyboard element for the notification and constrained it to the superview.  When the notification appears I see the window with nothing it it, but the view is the color of superview.  It's like the TimelineView is getting lost entirely and not displaying at all.

**Comment by grosch** [comment]
OK, it just really doesn't like coming from the storyboard.  I moved it back into code and implemented a slightly different viewDidLayoutSubviews and now it seems to be working great.  Thanks!

**Comment by richardtop** [comment]
Hi @grosch, the CalendarKit _should_ support Storyboards and Interface Builder, but has never been tested with it.

It's recommended that you configure the calendar with code.

Could you please share the implementation of your `layoutSubviews` method here?

**Comment by grosch** [comment]
```swift
  override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()

    let size = CGSize(width: view.width, height: view.height)
    timelineContainer.frame = CGRect(origin: CGPoint.zero, size: size)
  }
```

**Comment by richardtop** [comment]
@grosch looks good.

Alternatively, you may connect the view in `loadView` method to skip layout calculation at all.
