### ISSUE TITLE
Change first day start of week

### ISSUE THREAD

**Issue by zungx** [richardtop/CalendarKit#157]
Thanks for sharing the CalendarKit 
I don't want use default first day start. I want set monday start of week.
Thank you.

**Comment by richardtop** [comment]
Hi, @zungx currently CalendarKit takes the 1st day of the week form the user's default calendar settings. Would you like to override this behavior?

**Comment by zungx** [comment]
Hi @richardtop 
I know CalendarKit use user's default calendar settings, but i want fixed day start always is Monday.
I try add extension to change firstweekday 
`extension Calendar {
    var firstWeekday: Int { return 2 }
}
`
Everything ok. but have bug. 
when i scroll from Monday to Sunday not reload date cell data. I scroll from 28/05/2018 to 27/05/2018.
See on video https://drive.google.com/file/d/1Hqa2FKVumXftSwvn7nGcs0WgurJS8R0Q/view?usp=sharing
Thank you so much.

**Comment by richardtop** [comment]
This behavior is not supported currently. I'll mark it as an enchancement.

**Comment by richardtop** [comment]
It's possible in the current release of the CalendarKit by configuring it with the custom calendar.

![Simulator Screen Shot - iPhone 11 Pro - 2019-12-19 at 00 47 11](https://user-images.githubusercontent.com/8013017/71129912-4071e200-21f9-11ea-8de8-66e40ea806b7.png)
