### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mn288** [richardtop/CalendarKit#161]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

I am trying to have RTL Support( Scrolling Right to Left) for CalendarKit in my app. Is it supported?

**Comment by richardtop** [comment]
Hi @mn288, currently I have no evidence, whether CK supports RTL languages.

Feel free to test it out and submit a pull request if you wish to add such a feature.

**Comment by orihpt** [comment]
I'm working on RTL support and I'll open a pull request when I'm done
