### ISSUE TITLE
Question: Current time line show on incorrect position!!

### ISSUE THREAD

**Issue by fatenumber25** [richardtop/CalendarKit#164]
First thanks very much for so useful Library.

I’m working on customizing CalendarKit. And when i’m changed default timezone of application to GMT using 
NSTimeZone* GMT = [NSTimeZone timeZoneWithAbbreviation:@"GMT"];
[NSTimeZone setDefaultTimeZone:GMT];

The today current time line shown on incorrect position as bellow. 
![6283c0db-10e5-4817-be73-e5f95efead9e](https://user-images.githubusercontent.com/22123971/43031411-fef15f1c-8cdb-11e8-82ac-a35c5ac62694.png)

I’m focus on TimelineView.swift’s
var currentTime: Date {
    return Date()
}
but i don’t know how to fix. Could you help me that please?

**Comment by richardtop** [comment]
@fatenumber25 this feature is not supported.
I'm planning to fix the bug this week. Thank you for the report.

**Comment by fatenumber25** [comment]
@richardtop Thanks for your reply :)
Happy to wait your update!!

**Comment by richardtop** [comment]
@fatenumber25 could you please check whether the bug has been fixed in the master branch of this repository?

For integration assistance refer to ["How to install a pod from a specific branch?
"](https://stackoverflow.com/questions/39930664/how-to-install-a-pod-from-a-specific-branch)
