### ISSUE TITLE
Multiple EventViews get's created 

### ISSUE THREAD

**Issue by mahanthesh0r** [richardtop/CalendarKit#168]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
When ever i try to create a event there'll be multiple events that is getting created for the same time and date. I think the startDate and EndDate gets called multiple times..
Probably im doing something wrong here.I'm just not able to see it where :/

##### Code I'm using with CalendarKit

```Swift
//Event for date
    var events = [Event]()
    override func eventsForDate(_ date: Date) -> [EventDescriptor]
    {
                let dateFormatter = DateFormatter()
                dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
                dateFormatter.timeZone = TimeZone(abbreviation: "GMT+5:5")
                let event = Event()
                event.startDate = dateFormatter.date(from: "2018-09-05 3:30:00")!
                event.endDate = dateFormatter.date(from: "2018-09-05 6:30:00")!
                 event.text = "test"
                 self.events.append(event)
                return events
}

```
this is what im getting

![45096194-9d996f80-b13d-11e8-8cbe-3763158aeb48](https://user-images.githubusercontent.com/36630433/45261489-5e12a200-b421-11e8-8513-2b69d0aa740e.png)

**Comment by mahanthesh0r** [comment]
Can you please give me an example ?

**Comment by johnnyperdomo** [comment]
@mahanthesh0r I think the issue you're having is because of a for loop which creates multiple events. Is there a ***for loop*** in your code? 
```swift
for i in 0...4 {
let events = Event()
}
```
**If so...remove the *for loop* and change it to the code below**
```swift
let events = Event()
//etc...
```
this should fix the issue, and only give you one event

**Comment by richardtop** [comment]
@johnnyperdomo, @mahanthesh0r or this;
```Swift
//Event for date
    var events = [Event]() // Outer scope variable
    override func eventsForDate(_ date: Date) -> [EventDescriptor]
    {
                let dateFormatter = DateFormatter()
                dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
                dateFormatter.timeZone = TimeZone(abbreviation: "GMT+5:5")
                let event = Event()
                event.startDate = dateFormatter.date(from: "2018-09-05 3:30:00")!
                event.endDate = dateFormatter.date(from: "2018-09-05 6:30:00")!
                 event.text = "test"
                 self.events.append(event) // Events just get appended over and over again
                return events // The outer array is returned
}
```

**Comment by mahanthesh0r** [comment]
@richardtop You were right. It was a dumb mistake.. It works now!! Thank You
