### ISSUE TITLE
Remove Neon library dependency

### ISSUE THREAD

**Issue by richardtop** [richardtop/CalendarKit#170]

**Comment by IronMaltes** [comment]
Hi Richard, I understand you plan to drop Neon because is not being updated anymore, it seems abandoned by his author, right?

**Comment by richardtop** [comment]
Yes, that’s the idea. Also, it’s incompatible with swift package manager and other platforms (macOS).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by IronMaltes** [comment]
Yea, I've seen it. Are you going switch to another library or put the functionalities into the library?
I'm asking this because I'm also using it in my project, and actually was a nice help

**Comment by richardtop** [comment]
I'll leverage AutoLayout to replace Neon.
You'll still be able to use Neon in your project by importing it directly via CocoaPods.
