### ISSUE TITLE
Calendarkit cant build in xcode 10 - Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2

### ISSUE THREAD

**Issue by johnnyperdomo** [richardtop/CalendarKit#172]
##### Code I'm using with CalendarKit
```Swift
import CalendarKit
import DateToolsSwift

```
When trying to import modules in xcode 10 i get this message: 

**"Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler:"**

**Comment by richardtop** [comment]
More info needed to reproduce the issue. Works perfectly with my Xcode 10 Release.

**Comment by sima94** [comment]
@johnnyperdomo Try to delete xCode derivedData

**Comment by johnnyperdomo** [comment]
it works now, just needed to clean and build the project files.
