### ISSUE TITLE
Expanding day view in specific hour intervals

### ISSUE THREAD

**Issue by Terekness** [richardtop/CalendarKit#173]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

I'd like to start with saying that this library is awesome to work with, so thank you very much for making my life much easier.

My issue is actually more like a feature request. 
I'm solely using the day view, and I'd like to show all the things I've done throughout the day. Some things can take hours, other only a couple of minutes.
Adding events to the day view that lasts longer  than about 30 minutes shows up just fine, but any less than that and it'll be so small that it will barely show up (and won't show up at all if something only lasts a minute).

I know about the timeline verticalDiff variable, but having to change it to also be able to see events that last a minute, will make the rest of the day enormous, which isn't something I want.

Therefore my suggestion; would it be possible to "extend" the hours that have very small events in it (so perhaps increasing the verticalDiff drastically only in that timeslot), but keep the same verticalDiff for hour intervals that have longer events in them?

I've attached a screenshot of what I was thinking below.

#### Result I am trying to achieve

![calendar3](https://user-images.githubusercontent.com/5940867/45745018-2b765f80-bc00-11e8-8cae-28a2b6af8d5c.png)

**Comment by Terekness** [comment]
Another idea that popped up was also just using the pinch gesture to increase or decrease the verticalDiff, as in to simulate zooming in.

**Comment by richardtop** [comment]
Closing this issue in favor of #58, as it would solve the problem.
