### ISSUE TITLE
how to set calendar start date and end date

### ISSUE THREAD

**Issue by NithiTM** [richardtop/CalendarKit#174]
### New Issue Checklist

- [ ] Use the latest version of CalendarKit
- [ ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Duplicate of #54
