### ISSUE TITLE
Always calling override func eventsForDate(_ date: Date) -> [EventDescriptor]

### ISSUE THREAD

**Issue by Srinivasan27** [richardtop/CalendarKit#177]
### New Issue Checklist

- [ ] Use the latest version of CalendarKit
- [ ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
That's correct.

**Comment by richardtop** [comment]
You shouldn't. That's expected behavior. You override that method and populate your own events. The default implementation just returns an empty array.

**Comment by Srinivasan27** [comment]
Thanks mate. I fixed though

**Comment by Srinivasan27** [comment]
Hi there! I'm facing problem that events not generated after the successful call on API from server.
How to sync event call and API data model?
