### ISSUE TITLE
How to know if user tap on time where event is not added?

### ISSUE THREAD

**Issue by qasimsqm** [richardtop/CalendarKit#179]
### New Issue Checklist

- [x] Use the latest version of CalendarKit

##### Code I'm using with CalendarKit latest version

I need to let user add new events where events are not already added

**Comment by richardtop** [comment]
Use this method of `DayViewDelegate`:
```Swift
  func dayViewDidLongPressTimelineAtHour(_ hour: Int)
```

**Comment by qasimsqm** [comment]
Yes I got that but what if I want to get single tap?

**Comment by richardtop** [comment]
There is no way to do it.
You could add this functionality and submit a pull request, or just subclass DayView and add a tap gesture recognizer.
