### ISSUE TITLE
All-day tasks

### ISSUE THREAD

**Issue by s4x** [richardtop/CalendarKit#18]
Hi!
Refer to apple calendar app, we need place to show all-day tasks at the bottom of timeline.

**Comment by richardtop** [comment]
Good idea. Here is the example when there are multiple all-day events:
![photo_2017-02-11_22-25-02](https://cloud.githubusercontent.com/assets/8013017/22856744/036e3a5e-f0a9-11e6-94fc-e56cdce16711.jpg)

It's only a scrollview and events are stacked in a grid. I'll take on it soon. If you want, feel free to submit a pull request.

**Comment by LinnierGames** [comment]
Hola @richardtop I noticed this, and other issues, is still open.

I just began using this **amazingly** easy to use tool and would love to implement this perhaps myself. Any tips on what classes to look? I would say I've been using swift enough to say I'm at an intermediate level :3

**Comment by richardtop** [comment]
Hi Erik, it sounds good.

Here is a quick overview on how to implement this feature. I need it too, so your pull request is welcomed!

1. Add an `isAllDay` property to the `EventDescriptor` protocol and `Event`
2. In `TimelineView` in `recalculateEventLayout` split events into 2 categories: `allDay` and the rest. Handle `The rest` the usual way
3. For the `AllDay` events configure a separate view and place it on top of the Timeline, respecting the insets.
4. The interface for the `AllDayView` should accept an arbitrary number of the `EventDescriptor` objects and show the resulting view.



I'd go with a `UIStackView` inside `UIScrollView` approach.

So, we'll have the following view hierarchy:
AllDayEventView
 - UIScrollView
  - Vertical StackView
       - Horizontal StackView
       - Horizontal StackView
       - Horizontal StackView
       - Horizontal StackView

**Comment by LinnierGames** [comment]
This is great!! Deeply sorry for the late response, I’m enrolled in a two year boot camp in sf and our “open house”/“reversed job fair” is VERY soon

But! I’ll be tackling this very soon!
