### ISSUE TITLE
How to disable left right swipe of timeline?

### ISSUE THREAD

**Issue by qasimsqm** [richardtop/CalendarKit#180]
Hi can anyone tell me how can I disable left and right swipes in timeline?

**Comment by richardtop** [comment]
You'll need to create your own `DayView` from the CalendarKit components to achieve that functionality.

**Comment by qasimsqm** [comment]
Thanks but What are the attributes to disable?

**Comment by richardtop** [comment]
@qasimsqm there are two options you can try:
1. disable scrolling in all PagingViews and hide header
2. Re-create DayView from other components (i.e. just use the timeline, add it to subview, introduce delegate methods etc, except this new `NonScrollableDayView` would not be scrollable ;) )

But first, I'd like to hear more details about the result you're trying to achieve:
Should the calendar show just a single page? Or should be there an option to navigate between the dates?

**Comment by qasimsqm** [comment]
> @qasimsqm there are two options you can try:
> 
> 1. disable scrolling in all PagingViews and hide header
> 2. Re-create DayView from other components (i.e. just use the timeline, add it to subview, introduce delegate methods etc, except this new `NonScrollableDayView` would not be scrollable ;) )
> 
> But first, I'd like to hear more details about the result you're trying to achieve:
> Should the calendar show just a single page? Or should be there an option to navigate between the dates?

Thanks for reply Rechard. I want to navigate on different pages by tapping on date only not by swiping.

**Comment by richardtop** [comment]
Then its all the way to go to designing and creating your custom `TimelinePagerView` and using it in your new `DayView`
