### ISSUE TITLE
How to disable Overlapping Events?

### ISSUE THREAD

**Issue by dmaulikr** [richardtop/CalendarKit#181]
Hello,
I'm developing an App where I don't want to allow events to be overlapped on each other and in simple word I want to prevent user from adding events which overlaps on each other. 

suppose if one event is there for 4pm to 6pm and if I try to add new one from 3pm to 6pm which means it will overlap on previous one I want to prevent that overlapping. 

How can I achieve this?

**Comment by richardtop** [comment]
Hi, its a logic issue, not the UI. Simply disable adding event if it overlaps with the previous one. Or would you like to add some UI features to signal the possibility of adding a new event to some place?

Would be fantastic if you could put some UI mockups of what you'd like to achieve.

**Comment by dmaulikr** [comment]
hello i've another question is there any update about #58

**Comment by richardtop** [comment]
@dmaulikr no, there is no update on that issue.
