### ISSUE TITLE
Disable Full Screen Calendar

### ISSUE THREAD

**Issue by martinmaly21** [richardtop/CalendarKit#187]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Hello, 

This may be more of a question rather than an issue. However I feel as though it may help other users since it seemed as though there was a similiar question that never got answered. So basically the calendar looks good except it covers the entire screen (safe area included). Would there be any way in which I could possibly use constraints to ensure the calendar only goes up to a certain height. I have attached a picture to hopefully make my issue more clear. 

<img width="323" alt="screen shot 2019-01-06 at 7 37 49 pm" src="https://user-images.githubusercontent.com/40171261/50743985-20b1fb80-11ec-11e9-9049-288850c10424.png">

Most appreciated. 

##### Code I'm using with CalendarKit

```Swift

I have no code, I merely subclassed 'DayViewController'

```
#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]
<img width="241" alt="screen shot 2019-01-06 at 7 49 29 pm" src="https://user-images.githubusercontent.com/40171261/50743992-34f5f880-11ec-11e9-9774-77bee4a09bf3.png">
Please disregard the format of the calendar.

**Comment by martinmaly21** [comment]
Also, is there any way in which to add a button ontop of the calender? (for example the circular button located in the bottom right of the screen of my mockup) Because currently they do not show up when I place them in the storyboard. (I have tried bringing subviews to front).

**Comment by martinmaly21** [comment]
Also, how do I access the width of the calendar. Calling 'dayView.bounds.width' or 'dayView.frame.width' does not appear to work.

**Comment by kaizer122** [comment]
2

**Comment by hexpl0it** [comment]
For solve this problem I used a container view

**Comment by richardtop** [comment]
Fixed in [0.7.2](https://github.com/richardtop/CalendarKit/tree/0.7.2).
If the bug reappears, please add a comment here or create a new issue.

**Comment by jackspa22ow** [comment]
> To solve this problem I used a container view
Can you please tell me how can I use that?
I am facing the same problem.

Thanks in advance.
