### ISSUE TITLE
How to achieve this using Calendar kit 

### ISSUE THREAD

**Issue by sanathterli** [richardtop/CalendarKit#188]
![device-2019-01-07-154416](https://user-images.githubusercontent.com/27924116/50763282-59f27600-1295-11e9-9d62-6c276d80f3f0.png)

**Comment by richardtop** [comment]
More details needed

**Comment by sanathterli** [comment]
How to create a view above the calendar(Like shown above...selfAppointments/seekerApt.) ? with a button action ?
