### ISSUE TITLE
DayViewController with async data?

### ISSUE THREAD

**Issue by zvjerka24** [richardtop/CalendarKit#194]
Hi @richardtop is there ability to feed DayViewController with async data?

I wanted to block execution until data retrieved but this method is called on main thread
```
override func eventsForDate(_ date: Date) -> [EventDescriptor] {
....
    dataSource?.timePeriodsFor(date, completion: { (timePeriods) in
        // fill events
    }
    // wait until events filled
    return events
}
```

**Comment by richardtop** [comment]
Hi,
start fetching the data, then dispatch to the main thread and invoke `reloadData()` as in case with `UITableView` or `UICollectionView`.

**Comment by zvjerka24** [comment]
Hi,
that is exactly what I did at last :)

Thank you!

**Comment by polymorphia** [comment]
Sorry, can anyone post an example of this?
