### ISSUE TITLE
Stacking Issue

### ISSUE THREAD

**Issue by stomper3579** [richardtop/CalendarKit#196]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

I'm seeing a weird stacking issue.  Events that don't overlap are not stacking on top of each other.  Anyone else seeing this?

<img width="488" alt="screen shot 2019-02-19 at 3 22 32 pm" src="https://user-images.githubusercontent.com/25698045/53054866-b0d59880-345a-11e9-9b6e-978eb2b3a5e4.png">

**Comment by richardtop** [comment]
Please, provide the code and specific event dates which lead to this error.

**Comment by richardtop** [comment]
Relevant issue #113

**Comment by richardtop** [comment]
Closed as a duplicate
