### ISSUE TITLE
Top dates scroller not only by dates but years/months/weeks

### ISSUE THREAD

**Issue by mangen** [richardtop/CalendarKit#197]
Hello,

First of all thanks a lot for gorgeous pod, I love it. Just started to study it and have a question. 

Is it possible to present top navigation scroller not only by dates, but also by weeks/months/years?
<img width="257" alt="screen shot 2019-02-20 at 13 19 13" src="https://user-images.githubusercontent.com/1110959/53121837-61eb3a00-3512-11e9-9f5e-393deb6c724b.png">

Thanks in advance!

**Comment by richardtop** [comment]
Please, provide an UI mockup for the desired behavior.

**Comment by ghousesgb** [comment]
Could we have calendar view with month, year alone with week

**Comment by richardtop** [comment]
@ghousesgb please, elaborate on what you're trying to achieve.

**Comment by Rohan29** [comment]
Hi  @richardtop ,
Want to create monthlyView to select date.
![Screenshot 2019-06-10 at 2 55 36 PM](https://user-images.githubusercontent.com/23051728/59186238-01027300-8b90-11e9-815b-fa7e1530ffc0.png)

**Comment by Rohan29** [comment]
Hi @richardtop , i want to implement same functionality with month View
Thanks

**Comment by richardtop** [comment]
@Rohan29  you'll need to use a different library for the Month view and integrate the month component together with the CalendarKit. E.g. show month view when the user taps on the button in the navigation bar. CK is currently all about the DayView and doesn't support month / year views.

**Comment by Rohan29** [comment]
Hi @richardtop, thanks for responding ,I have used **VACalender**  to achieve desired result.

**Comment by richardtop** [comment]
Great!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
