### ISSUE TITLE
2 days Event object is not set properly

### ISSUE THREAD

**Issue by nastasiupta** [richardtop/CalendarKit#198]
### New Issue Checklist

- [ x ] Use the latest version of CalendarKit
- [ x ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ x ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Demo: https://drive.google.com/file/d/1q_pUS-y5HmiOtQRocJ16xRvMWVvin357/view?usp=sharing
In the following example, I have one event starting at 19 Feb 16:24 and ends at 20 Feb 16:24 (24 hours event).
As you can see, in the video, if first I open 19 February, the event object start time is not set correctly. Also if I go to 20th and then I turn back to 19th, this issue is fixed. Also if I go back to 20 Feb the issue is fixed.

PS: If the event is starting and ends on the same day, everything is fine.

##### Code I'm using with CalendarKit

This is how I create an Event object:

```Swift

let event = Event()
if let startTimeInt = model.startTimeInt, let endTimeInt = model.endTimeInt {
                
    let startDate = Date(timeIntervalSince1970: TimeInterval(startTimeInt))
    let endDate =  Date(timeIntervalSince1970: TimeInterval(endTimeInt))

    event.startDate = startDate
    event.endDate = endDate
    event.eventType = "\(model.availabilityID ?? 0)"

    if model.typeEvent == "5" {
        var info = ["\(model.startLoc!)","\(startDate.format(with: "EEE. d MMM - hh:mm a"))" ," ",
                    "\(model.endLoc!) ", "\(endDate.format(with: "EEE. d MMM - hh:mm a"))"]
        info.append("")
        // Set "text" value of event by formatting all the information needed for display
        event.text = info.reduce("", {$0 + $1 + "\n"})
    } else {
        var info = ["\(model.startLoc!) -LOAD","\(startDate.format(with: "EEE. d MMM - hh:mm a"))" ," ",
                    "\(model.endLoc!) -DISCHARGE", "\(endDate.format(with: "EEE. d MMM - hh:mm a"))"]
        info.append("")
        // Set "text" value of event by formatting all the information needed for display
        event.text = info.reduce("", {$0 + $1 + "\n"})
    }

    event.color = colors[model.Color!]
    events.append(event)
}

```

#### Result I am trying to achieve

Demo: https://drive.google.com/file/d/1q_pUS-y5HmiOtQRocJ16xRvMWVvin357/view?usp=sharing

The calendar events should be displayed properly when I first tap on them without having to switch from one day to another.

**Comment by richardtop** [comment]
Please, upload your files again.
