### ISSUE TITLE
How to show only hourly calendar?

### ISSUE THREAD

**Issue by sariminapp** [richardtop/CalendarKit#199]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

func eventsForDate(_ date: Date) -> [EventDescriptor] {
        var events = [Event]()
        
        for i in 0..<titlesArray!.count {
            print(i)
            let event = Event()
            // Specify StartDate and EndDate
            event.startDate = Constant.convertStringToDatewithFormat(dateString: "\(dateChoosen) \(startDateArray![i])", format: "d MMMM yyyy HH:mm")
            event.endDate = Constant.convertStringToDatewithFormat(dateString: "\(dateChoosen) \(endDateArray![i])", format: "d MMMM yyyy HH:mm")
            // Add info: event title, subtitle, location to the array of Strings
            var info = [titlesArray![i], locationArray![i]]
            info.append("\(startDateArray![i]) - \(endDateArray![i])")
            // Set "text" value of event by formatting all the information needed for display
            event.text = info.reduce("", {$0 + $1 + "\n"})
            events.append(event)
        }
        return events
    }

```

#### Result I am trying to achieve

![WhatIWant](https://user-images.githubusercontent.com/31340076/54173457-a7b57580-44b4-11e9-891a-87dd90b27e96.jpg)

How to costumize only show hourly calendar event?

**Comment by richardtop** [comment]
Please, provide an UI mockup, and/or more detailed description of what you're trying to achieve.

**Comment by sariminapp** [comment]
Thanks for replying,
Here are the mockup. First I create monthly calendar. The dot in calendar mean that date have event. Only date with dot can be clicked. When clicked, I sent data to detail event page:
1. date choosen (as string)
2. start event hour:minutes (as array string)
3. end event hour:minutes (as array string)
4. event title (as array string)
5. event all day event (as array boolean)
6. event location (as array string)
7. event notes (as array string)

![simulator screen shot - iphone 8 plus - 2019-01-30 at 00 13 36](https://user-images.githubusercontent.com/31340076/53925169-941f9e80-40b1-11e9-9477-351fc0cedb76.png)
![simulator screen shot - iphone 8 plus - 2019-01-30 at 00 13 39](https://user-images.githubusercontent.com/31340076/53925189-a00b6080-40b1-11e9-96d7-beff3d4778aa.png)

I want to change hourly event use hourly event list like in Calendar Kit.
So how to costumize only show hourly calendar event?

Regards,
Sarimin App

**Comment by ivankriak** [comment]
`dayView.isHeaderViewVisible = false`
