### ISSUE TITLE
How to usage

### ISSUE THREAD

**Issue by onurgurbuz** [richardtop/CalendarKit#20]
Is there any video about how to usage and how to setup this?

**Comment by richardtop** [comment]
@onurgurbuz is there something unclear after reading [this part of the Readme](https://github.com/richardtop/CalendarKit#usage)?

**Comment by onurgurbuz** [comment]
@richardtop thanks. i did. 
i think it would be good if it was usage and example video

**Comment by richardtop** [comment]
@onurgurbuz I will add a video later. Right now I have some thoughts on decoupling interface from EventView, so the usage pattern of this library might change.

**Comment by onurgurbuz** [comment]
@richardtop we are waiting. i will use that some project. if can i help anything i can. good works.

**Comment by richardtop** [comment]
@onurgurbuz Thanks. You can use the library even at this stage, as the interface will change only slightly.
