### ISSUE TITLE
How to set frame of custom events in TimelineView according to StartTime and EndTime

### ISSUE THREAD

**Issue by sanathterli** [richardtop/CalendarKit#203]

**Comment by sanathterli** [comment]
![device-2019-01-07-154416](https://user-images.githubusercontent.com/27924116/55535705-8ae81880-56d5-11e9-9833-15d0e77eb0f8.png)
I need to achieve, This with start and end time in TimeLineView by changing the frame(x,y,width,height)

**Comment by richardtop** [comment]
This is impossible. The only way to change event's layout is to change it's `startDate` and `endDate` properties while returning an `event` object in `eventsForDate` method.

To achieve the following layout, you'll need to create events with an evenly spaced interval, e.g. 20 minutes:

```
Event 1:
     Start: 00:00
     End: 00:20

Event 2:
     Start: 00:30
     End: 00:40

Event 3:
     Start: 00:40
     End: 01:00

Event 4: ...
```
However, it's impossible to do lay out events using just frames.
