### ISSUE TITLE
How to add a segmented controller in the view ??

### ISSUE THREAD

**Issue by aymenbraham** [richardtop/CalendarKit#204]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [ ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Please provide UI mockups or more detailed description of what you're trying to achieve.
