### ISSUE TITLE
Removal of PagingScrollView

### ISSUE THREAD

**Issue by bWheeler1977** [richardtop/CalendarKit#207]
### New Issue Checklist

- [ ] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
So, with the update from 0.6.0 to 0.6.1 and now 0.7.0, I see that PagingScrollView was removed. When it was in, if a user swiped in the Day View, or tapped a new day in the Day Header, it would eventually trickle down the calls to the DayView.timelinePager delegate and to the dayView.didMoveTo call, which we then defined to update the data for the new day.

Now with the removal of PagingScrollView, only swiping of the Day View to a new day is trickling down to the dayView.didMoveTo method and updating the data for the new day. Tapping on a day in the header is not doing anything, the new day view loads in empty.

#### Result I am trying to achieve
I'm just wondering if there is another way that I'm not aware of, or didn't notice, to have the day header send the call to the dayView.didMoveTo method so that we can update the view with the new day's data? Is there another delegate I have to define to get that to happen, or is that functionality just not there anymore? And if it isn't there, will it be added in the future?

Right now, we switched back to using version 0.6.0, but would like to update to the latest if there is a way to update data when tapping on a new day in the header.

Thanks

**Comment by richardtop** [comment]
Fixed in [0.7.1](https://github.com/richardtop/CalendarKit/tree/0.7.1).
Please, let me know, if the issue still persists.
