### ISSUE TITLE
dayView.autoScrollToFirstEvent = true does not scroll timeline when tapping in week header

### ISSUE THREAD

**Issue by ServicePal** [richardtop/CalendarKit#208]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Small regression in 0.7.0. 
When using dayView.autoScrollToFirstEvent = true the timelineView is only scrolling when you swipe left/right on the view, not when you tap a day in the week header. It used to do that.

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]


#### Result I am trying to achieve
<!-- If you have a UI Mockup of what you're trying to achieve, please, paste it here (Optional) -->
[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Fixed in [0.7.1](https://github.com/richardtop/CalendarKit/tree/0.7.1).
Please, let me know, if the issue still persists.
