### ISSUE TITLE
How can I translate days into another language?

### ISSUE THREAD

**Issue by bahaTRKGLU** [richardtop/CalendarKit#209]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
It should be available by default, just change the app's language to the desired one.

**Comment by bahaTRKGLU** [comment]
thank you so much.
