### ISSUE TITLE
Current Time 12/24 hour issue

### ISSUE THREAD

**Issue by omerbaskurt** [richardtop/CalendarKit#213]
### New Issue Checklist

- [ ] Use the latest version of CalendarKit
- [ ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift
let currentTimeIndicatorStyle = CurrentTimeIndicatorStyle()
currentTimeIndicatorStyle.dateStyle = .twelveHour
let timelineStyle = TimelineStyle()
timelineStyle.dateStyle = .twelveHour
timelineStyle.timeIndicator = currentTimeIndicatorStyle
let style = CalendarStyle()
style.timeline = timelineStyle
dayView.updateStyle(style)
```

#### Result I am trying to achieve
I want to show the current time in 12-hour format. The result gives me system's format.
Timeline style shows 12-hour format correctly.

**Comment by richardtop** [comment]
The issue isn't reproducible with the code attached when put into the `viewWillAppear` method:
```Swift
  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    let currentTimeIndicatorStyle = CurrentTimeIndicatorStyle()
    currentTimeIndicatorStyle.dateStyle = .twelveHour
    let timelineStyle = TimelineStyle()
    timelineStyle.dateStyle = .twelveHour
    timelineStyle.timeIndicator = currentTimeIndicatorStyle
    let style = CalendarStyle()
    style.timeline = timelineStyle
    dayView.updateStyle(style)
  }
```

Result:

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-09 at 00 37 14](https://user-images.githubusercontent.com/8013017/72022082-45fe9d00-3278-11ea-841e-eb9bdc959cda.png)
