### ISSUE TITLE
Event stopping on now line

### ISSUE THREAD

**Issue by jmanoel** [richardtop/CalendarKit#215]
Hello. I created an event that will go until 23:59. But it only show until now Line.

How can I resolve this issue?
<img width="387" alt="Captura de Tela 2019-07-03 às 21 51 49" src="https://user-images.githubusercontent.com/4211703/60632572-cbdaf080-9ddc-11e9-8039-216518e07137.png">

**Comment by richardtop** [comment]
@jmanoel how did you solve the issue?

**Comment by jmanoel** [comment]
Hello. Was my mistake. I Was creating a wrong end time event and It was replacing by current date
