### ISSUE TITLE
willMoveTo executed twice each time.

### ISSUE THREAD

**Issue by aniq-pirzada** [richardtop/CalendarKit#221]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Is there a way to remove the timeline and just use the header only to select dates.

##### Code I'm using with CalendarKit
I can comment out 
```Swift
addSubview(timelinePagerView) 
```
in the DayView.swift  in the CalendarKitDemo but when I do this in my own project it does not work.

#### Result I am trying to achieve
What I am trying to achieve:
![Screenshot 2019-08-04 at 9 57 48 pm](https://user-images.githubusercontent.com/11415321/62429518-99882000-b707-11e9-8571-a3ff79af876d.png)

what my project one looks 
![Screenshot 2019-08-04 at 9 58 17 pm](https://user-images.githubusercontent.com/11415321/62429517-94c36c00-b707-11e9-8ac3-24cf3df7e768.png)

**Comment by aniq-pirzada** [comment]
I have fixed the issue by rebuilding the pods - but now I am having another problem.
I have added a View into my storyboard which has the custom class: 'DayView'
I implemented DayViewDelegate which has the standard stubs including:

```swift
func dayView(dayView: DayView, willMoveTo date: Date) {
        print("Will Move to: \(date)")
    }
```

But when selecting a day the function willMoveTo executed twice each time.
For example the output I am getting is:
``` 
Will Move to: 2019-08-05 23:00:00 +0000
Will Move to: 2019-08-05 23:00:00 +0000
```

**Comment by richardtop** [comment]
This issue has been fixed in the latest release of the CalendarKit:

```Swift
  public func move(from oldDate: Date, to newDate: Date) {
    let oldDate = oldDate.dateOnly(calendar: calendar)
    let newDate = newDate.dateOnly(calendar: calendar)
    let newController = configureTimelineController(date: newDate)

    delegate?.timelinePager(timelinePager: self, willMoveTo: newDate)

    func completionHandler(_ completion: Bool) {
      pagingViewController.viewControllers?.first?.view.setNeedsLayout()
      scrollToFirstEventIfNeeded()
      delegate?.timelinePager(timelinePager: self, didMoveTo: newDate) <------ Error was here
    }

    if newDate.isEarlier(than: oldDate) {
      pagingViewController.setViewControllers([newController], direction: .reverse, animated: true, completion: completionHandler(_:))
    } else if newDate.isLater(than: oldDate) {
      pagingViewController.setViewControllers([newController], direction: .forward, animated: true, completion: completionHandler(_:))
    }
  }
```
