### ISSUE TITLE
Expose tapped date on dayViewDidTapTimeline and dayViewDidTapTimeline

### ISSUE THREAD

**Issue by bithavoc** [richardtop/CalendarKit#224]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
I need to create events on single tap, for that I need the tapped date.

#### Code I'm using with CalendarKit

```Swift

func timelinePagerDidTap(timelinePager: TimelinePagerView)
func dayViewDidTapTimeline(dayView: DayView)
```

#### Result I am trying to achieve

```Swift
func timelinePagerDidTap(timelinePager: TimelinePagerView, date: Date)
func dayViewDidTapTimeline(dayView: DayView, date: Date)
```

I can send a PR with these *breaking* changes.

**Comment by richardtop** [comment]
Great idea. Please, refer to the `didLongPressTimeline at date` for the inspiration.
If there is some common code between those two methods, please extract it to the private methods inside respective classes.
