### ISSUE TITLE
I just need Timeline view not with the calendar. Is there any possibilities?

### ISSUE THREAD

**Issue by SunnyBamaniya** [richardtop/CalendarKit#226]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Hi, just use the components then, not the whole `DayViewController`.
See example in [ExampleNotificationController](https://github.com/richardtop/CalendarKit/blob/master/CalendarKitDemo/CalendarKitDemo/ExampleNotificationController.swift)

**Comment by SunnyBamaniya** [comment]
Thanks @richardtop for the reply.
I used ExampleNotificationController but now we need to add Multiple events without using calendar.

Can you please just help to come out from the issue.
Thanks.

**Comment by richardtop** [comment]
Please, attach the screenshot or mockup of what you're trying to achieve.

**Comment by SunnyBamaniya** [comment]
![photo_2019-10-20 18 37 40](https://user-images.githubusercontent.com/5909435/67159933-c17f3b00-f368-11e9-9696-5b833dfcc278.jpeg)
We are trying something like it.
We already implemented in Android App.

**Comment by richardtop** [comment]
It doesn't show one event at a time, please check examples.
It shows any number of events you pass by the DayViewDataSource.

**Comment by SunnyBamaniya** [comment]
![image](https://user-images.githubusercontent.com/5909435/67161246-46248600-f376-11e9-800f-bdab6f365861.png)

this how we added the code
still not working.
can you let us know what the wrong thing i am doing.

**Comment by richardtop** [comment]
What is the contents of the array?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SunnyBamaniya** [comment]
How can we increase spacing (height) between to hours like 9:00 AM to 10:00?

![image](https://user-images.githubusercontent.com/5909435/67222611-49d60c80-f44b-11e9-8f99-681415150988.png)

**Comment by richardtop** [comment]
Take a look into verticalDiff property of the CalendarStyle 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SunnyBamaniya** [comment]
![image](https://user-images.githubusercontent.com/5909435/67272119-8fd9b180-f4d9-11e9-848d-ddda29b90755.png)

this is our code and we are unable to set data.
Can you just late us where i am wrong.

i also attach json file here.
[JSON.txt](https://github.com/richardtop/CalendarKit/files/3754570/JSON.txt)

**Comment by richardtop** [comment]
Please, configure an example project and attach it here, so I could run it locally.

**Comment by SunnyBamaniya** [comment]
Hello Richardtop,
Here i attach sample project.
also let us know how can i get value of selected timeline.

Thanks

[SampleTesting.zip](https://github.com/richardtop/CalendarKit/files/3755212/SampleTesting.zip)

**Comment by SunnyBamaniya** [comment]
Hello @richardtop 
Can have any feedback on above example?

**Comment by richardtop** [comment]
Hi, I hope to check it next week.

**Comment by richardtop** [comment]
[SampleTesting.zip](https://github.com/richardtop/CalendarKit/files/3806466/SampleTesting.zip)
@SunnyBamaniya  you had an error in layout. Please, learn more about UIKit and how to do manual / auto layout.

I fixed your issue to make the Calendar occupy the whole view.

**Comment by EAmey** [comment]
> Hi, just use the components then, not the whole `DayViewController`.
> See example in [ExampleNotificationController](https://github.com/richardtop/CalendarKit/blob/master/CalendarKitDemo/CalendarKitDemo/ExampleNotificationController.swift)


Hey @richardtop 

I tried this solutions and it's working perfectly. But is it possible to add multiple event for same datetime. Currently I have added 2 events and second one is with large duration but its overlapping first one. Can you help on this?

**Comment by richardtop** [comment]
Send a screenshot please. Definitely should be possible. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SunnyBamaniya** [comment]
Hi @EAmey 
Can you share your example?
How you set 2 events using ExampleNotificationController.

**Comment by SunnyBamaniya** [comment]
Hello @richardtop 
I just want to add multiple events using ExampleNotificationController.

here I tried in ViewController.swift but unable to add multiple events.
[SampleCalendar.zip](https://github.com/richardtop/CalendarKit/files/3814287/SampleCalendar.zip)

**Comment by EAmey** [comment]
> Hi @EAmey
> Can you share your example?
> How you set 2 events using ExampleNotificationController.

Please find below code

 if let arrTask = TimesheetTasks.getEventsForDate(date: timelineContainer.timeline.date)
             {
                
                for task in arrTask
                {
                    //working with 12 hours format only

                  let event = Event()
                    event.startDate = task.startTime
                    event.endDate = task.endTime
                      event.textColor = .white
                      event.color = .red

                    var info = ["\(task.taskName ?? "Task")"]
                    info.append("\(task.projectName ?? "Project")")
                        info.append("\(task.startTime.format(with: "hh:mm")) - \(task.endTime.format(with: "hh:mm"))")
                        event.text = info.reduce("", {$0 + $1 + "\n"})
                                 
                    arrEvents.append(EventLayoutAttributes(event))
                }
                timelineContainer.timeline.layoutAttributes = arrEvents
                
                return
             }

**Comment by EAmey** [comment]
@SunnyBamaniya 
Please find code as below


 lazy var timelineContainer: TimelineContainer = {
        let timeline = TimelineView()
        timeline.frame.size.height = timeline.fullHeight
        timeline.eventViewDelegate = self
        var currentCalendar = Calendar(identifier: .gregorian)
           currentCalendar.locale = Locale.current
           currentCalendar.timeZone = TimeZone.current
          
        timeline.calendar = currentCalendar
        let timelineStyle = TimelineStyle()
        timelineStyle.dateStyle = .twelveHour
        //timelineStyle.verticalDiff = 60.0
        timeline.updateStyle(timelineStyle)
        let container = TimelineContainer(timeline)
        container.contentSize = timeline.frame.size
        container.backgroundColor = .white
        container.addSubview(timeline)
        container.isUserInteractionEnabled = true
        return container
      }()




 func getEventDataForDate()
    {
        timelineContainer.timeline.date = self.dateSelected ?? Date()
        timelineContainer.timeline.layoutAttributes.removeAll()
        if let arrTask = TimesheetTasks.getEventsForDate(date: timelineContainer.timeline.date)
             {
                
                for task in arrTask
                {
                    //working with 12 hours format only

                  let event = Event()
                    event.startDate = task.startTime
                    event.endDate = task.endTime
                      event.textColor = .white
                      event.color = .red

                    var info = ["\(task.taskName ?? "Task")"]
                    info.append("\(task.projectName ?? "Project")")
                        info.append("\(task.startTime.format(with: "hh:mm")) - \(task.endTime.format(with: "hh:mm"))")
                        event.text = info.reduce("", {$0 + $1 + "\n"})
                                 
                    arrEvents.append(EventLayoutAttributes(event))
                }
                timelineContainer.timeline.layoutAttributes = arrEvents
                
                return
             }
}

**Comment by SunnyBamaniya** [comment]
Hello @richardtop 
How can we configure timing instead of 12 am - 12 am to 09 AM - 06 PM?

**Comment by richardtop** [comment]
Currently it's impossible (see #34).
