### ISSUE TITLE
Russian localization 

### ISSUE THREAD

**Issue by fury21** [richardtop/CalendarKit#228]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Hi!
My iPhone have Russian localization, but some part of UI still in English. How can it fix?

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]
![IMG_0918](https://user-images.githubusercontent.com/30409500/67619206-494dc500-f801-11e9-9708-7e3e02cd27be.PNG)

**Comment by richardtop** [comment]
Hi, are you sure you’re supporting Russian locale in your app?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fury21** [comment]
What do you mean? On my iPhone, Russian localization is turned on. The entire interface is in Russian.

**Comment by richardtop** [comment]
Ok, a localization in the app target also has to be russian. Could you please attach a minimum reproducible example here as an archive?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fury21** [comment]
[Man School123.zip](https://github.com/richardtop/CalendarKit/files/3779190/Man.School123.zip)

ok

**Comment by richardtop** [comment]
Thanks, I’ll take a look this week.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richardtop** [comment]
Hi, you've forgot to include Russian in the target's development language:
<img width="1792" alt="Skärmavbild 2019-10-30 kl  01 32 25" src="https://user-images.githubusercontent.com/8013017/67817303-8c37c300-fab5-11e9-8652-30af7bad1354.png">

After that it's possible to run the app in the Russian locale and it displays day symbols also in Russian:
![IMG_2069](https://user-images.githubusercontent.com/8013017/67817385-d3be4f00-fab5-11e9-8834-0772b679d85f.PNG)
