### ISSUE TITLE
Implementation without subclassing view controller

### ISSUE THREAD

**Issue by diegorozen** [richardtop/CalendarKit#23]
Hello,

My understanding is that the library expects to be used by creating a view controller that subclasses DayViewController, taking the entire screen bounds. Is there a way to just use DayView in a region of the screen, with my view controller implementing DayViewDelegate?

Thanks!

**Comment by richardtop** [comment]
Of course, there is such an option.
Just add an instance of the [DayView](https://github.com/richardtop/CalendarKit/blob/master/Source/DayView.swift) to your view hierarchy and resize accordingly. Then, implement `DayViewDataSource` in some of your classes and assign it to the `DayView`.
Please, indicate, whether this resolved your issue.

**Comment by diegorozen** [comment]
Should weak var dataSource: DayViewDataSource? and weak var delegate: DayViewDelegate? be declared as public since they will be accessed from a different module?

**Comment by richardtop** [comment]
@diegorozen I've updated the pod, should be OK now. Could you try one more time? `pod update` will do the job.

**Comment by diegorozen** [comment]
That was fast, thanks!

**Comment by richardtop** [comment]
May I close this issue?

**Comment by diegorozen** [comment]
Please do
