### ISSUE TITLE
Use in navigation bar background color in light theme default color

### ISSUE THREAD

**Issue by fury21** [richardtop/CalendarKit#234]
### New Issue Checklist

- [ ] Use the latest version of CalendarKit
- [ ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Hi! How can i use in navigation bar background color in light theme default color?

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Your question is unclear. Please clarify it, or provide more context. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fury21** [comment]
I mean that now the background color is different from the default color. How do I change it? See the screenshots
![IMG_1273](https://user-images.githubusercontent.com/30409500/69616213-48e65b00-1047-11ea-9267-630d414e2a73.jpg)
![IMG_1274](https://user-images.githubusercontent.com/30409500/69616214-48e65b00-1047-11ea-8fa7-4431f33bcd2a.PNG)

**Comment by richardtop** [comment]
I think, you’re using a translucent navigation bar which causes such an effect.
Or something other is wrong in your navigation controller configuration. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
