### ISSUE TITLE
EventView - Edit TextView Frame?

### ISSUE THREAD

**Issue by payshake** [richardtop/CalendarKit#236]
Hey all,

I'm looking for what I hope is a simple fix. I'd like to remove the top padding of the event view, so that the TextView aligns more towards the top of the EventView, and not in the center as it does now.

Can anyone point me in the right direction?

**Comment by richardtop** [comment]
Hi, please show me graphic illustrations of what it is right now and what you’d like to achieve. Then I’ll be able to help 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by payshake** [comment]
> Hi, please show me graphic illustrations of what it is right now and what you’d like to achieve. Then I’ll be able to help
> 
> Sent with [GitHawk](http://githawk.com)

@richardtop Thank you for the quick reply! If you see the attached image, some of the shorter EventView's (20 mins or less) don't show the text, because of a top padding in the view.

Ultimately, I'd like to have the text hug the top part of the cell, so that it would always be visible (or even better, auto-adjust the font size to fit the view)

![IMG_0053](https://user-images.githubusercontent.com/53497146/69482375-de7fb180-0ddf-11ea-82d6-ab538b14016c.png)

**Comment by richardtop** [comment]
Have you considered changing the time interval between hours? That’s already implemented in the  library and would solve your problem.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richardtop** [comment]
Try:
```Swift
  override func viewDidLoad() {
    super.viewDidLoad()
    let style = StyleGenerator.defaultStyle()
    style.timeline.verticalInset = 90
    updateStyle(style)
}
```

in your `DayViewController`

**Comment by payshake** [comment]
@richardtop Perfect, thank you for the advice and awesome library! (let me know if I can donate via PayPal)

**Comment by richardtop** [comment]
Thank you! Hope you've resolved your issue. While changing the `verticalInset` would help in the short term, the long-term solution is to support connecting a custom view to the library, similarly to the `UITableViewCell` & `UICollectionViewCell` - there is already a ticket for it: #175.

For donations, please, contact me via [Telegram](t.me/richardtop),
or email: `topchiy` at domain `protonmail` dot `ch`.

**Comment by DevonAllary** [comment]
Hi Richard, is this still working in the latest version? I tried to implement this and I'm not seeing any changes.

**Comment by richardtop** [comment]
Please open a new issue with screenshots and sample code if you experience some bug.
