### ISSUE TITLE
Custom the DayHeaderView

### ISSUE THREAD

**Issue by Tawfikk** [richardtop/CalendarKit#240]
I have a question about `DayHeaderView`. Can I set is without `TimelinePagerView` and also, how customize it ?

<img width="486" alt="Screenshot 2019-12-17 10 07 13" src="https://user-images.githubusercontent.com/28268405/70972770-334bda80-20b5-11ea-970a-1790bff72f2c.png">

**Comment by Tawfikk** [comment]
@Rich86man

**Comment by richardtop** [comment]
Hi, currently there is no easy way to customize it beyond changing a style.
One of the option would be to to use the CalendarKit components to assemble own DayView.

E.g. in this example, you'll need to use `TimelinePagerView` and create own version of the `DayView`, using your custom header.
