### ISSUE TITLE
Adding Event to the UserDefaults

### ISSUE THREAD

**Issue by pradeepktg** [richardtop/CalendarKit#241]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [ ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Hi, Is there any way to add the Event to the UserDefaults? I tried to add but getting the below error
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object (
    "CalendarKit.Event"
) for key EventsList'
```

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

``` mutating func addEvent(_ event: Event){
        events.append(event)
        let defaults = UserDefaults.standard
            defaults.set(event, forKey: "EventsList")
    }


   mutating func getEvents() -> [Event] {
     
        let defaults = UserDefaults.standard
        if let savedEvents = defaults.object(forKey: "EventsList")  {
        
            events = savedEvents as! [Event]
         
        }
        
        return events
    }
#### Result I am trying to achieve
<!-- If you have a UI Mockup of what you're trying to achieve, please, paste it here (Optional) -->
[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Hi, the `Event` protocol doesn't allow persistence. You'll need to create your own code to store all of the values in the `Event` and restore it on app launch.

That could be JSON, CoreData or UserDefaults as you mentioned. However, this is out of scope of the CalendarKit. Please, ask your question on the StackOverflow using the `CalendarKit` tag.
