### ISSUE TITLE
Column Behavior

### ISSUE THREAD

**Issue by narmertechnology** [richardtop/CalendarKit#244]
We're using CalendarKit pretty heavily in our app (and loving it!), but we're seeing some inefficient behavior with the way the columns and rows are being displayed.

Please see below:

![IMG_0196](https://user-images.githubusercontent.com/52138958/73146957-b9771b80-407a-11ea-9c33-fe610bd272b2.png)

When compared with the Apple Calendar below, it seems some of the rows on CalendarKit that could be extending all the way to the edge of the view are only being displayed as small columns. Is there any way to achieve some form of what we see below?

![IMG_0199](https://user-images.githubusercontent.com/52138958/73147026-1bd01c00-407b-11ea-9d3f-e5e058ab8226.JPG)

**Comment by richardtop** [comment]
Hi, it's an error in the layout algorithm, already filed here: #113
While the algorithm works well for a small number non-overlapping events, it definitely has issues when the number of events grows large enough.

**Comment by richardtop** [comment]
#113
