### ISSUE TITLE
eventResizeHandles?

### ISSUE THREAD

**Issue by IronMaltes** [richardtop/CalendarKit#245]
Hi Richard!

I'm wondering why is this for: eventResizeHandles.forEach{addSubview($0)}
If seen that this creates the resizing handles when editing, but looks like is not fully implemented or am I missing something ?

Thanks a lot!

**Comment by richardtop** [comment]
Hi, you’re right, it’s a “deactivated” feature for now.
Are you using CalendarKit in one of your apps? I’d be happy to hear about the usage pattern, drop me a line to an email in my profile page.
Richard

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richardtop** [comment]
Fixed in [0.12.1](https://github.com/richardtop/CalendarKit/tree/0.12.1)
