### ISSUE TITLE
Can i change position of date from vertical to horizontal?

### ISSUE THREAD

**Issue by krutitrivedi** [richardtop/CalendarKit#247]
Hello, I want to change position of date list as attached screen short please guide me on how to achieve that design. ![Screenshot 2020-03-17 at 2 38 05 PM](https://user-images.githubusercontent.com/28212734/76840338-072f2980-685d-11ea-9c78-8f120ece51b7.png)

**Comment by richardtop** [comment]
Hi, this design goes beyond CalendarKit. The best way to achieve it is to create a `UITableView` with custom cell. I don't think CalendarKit could help you in this.

Feel free to close the issue if you have no further questions.

**Comment by krutitrivedi** [comment]
for tableview how can i derive dates? can you please help me on how to get list of dates

**Comment by richardtop** [comment]
Your design would require an instance of `UITableView`, then you'll need to implement some sort of the DataSource interface between your UI component and the rest of the application (similar to the `UITableViewDataSource` or `DayViewDataSource` in CalendarKit).

On the UI side, you'll need to create a cell layout.

The whole interface should refer to the `Calendar` as a model (or `NSCalendar` in Objective-C) and infer valid dates from the `Calendar` instance.
