### ISSUE TITLE
Multi day event title location

### ISSUE THREAD

**Issue by cstlex** [richardtop/CalendarKit#250]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Location of title label of EventView is hard to find on event with start time and end time in different date.
![screenshot](https://user-images.githubusercontent.com/6779864/77738112-a1be0400-6fe5-11ea-8539-e2c2ac3fc90e.png)

```
import CalendarKit;

class ViewController: DayViewController {

    override func viewDidLoad() {
        super.viewDidLoad();
    }
    
    override func eventsForDate(_ date: Date) -> [EventDescriptor] {
        let event = Event();
        event.startDate = Date().subtract(.init(seconds: 0, minutes: 0, hours: 0, days: 1, weeks: 0, months: 0, years: 0));
        event.endDate = Date();
        event.text = "Test";
        return [event];
    }
}
```

**Comment by richardtop** [comment]
Please, attach the code.

**Comment by cstlex** [comment]
```
import CalendarKit;

class ViewController: DayViewController {

    override func viewDidLoad() {
        super.viewDidLoad();
    }
    
    override func eventsForDate(_ date: Date) -> [EventDescriptor] {
        let event = Event();
        event.startDate = Date().subtract(.init(seconds: 0, minutes: 0, hours: 0, days: 1, weeks: 0, months: 0, years: 0));
        event.endDate = Date();
        event.text = "Test";
        return [event];
    }
}
```

**Comment by ServicePal** [comment]
This is a known issue where the event title is not showing across all days the event is planned for. It only shows on for the first day. Don't see it listed as an open issue, but thought it was already on the list.
