### ISSUE TITLE
dayView.autoScrollToFirstEvent = true does not scroll timeline when tapping in week header

### ISSUE THREAD

**Issue by lucaslupo** [richardtop/CalendarKit#256]
This doesn't seem to be fixed. https://github.com/richardtop/CalendarKit/issues/208

I can still reproduce on latest master: 0.12.3

**Comment by richardtop** [comment]
Could you please try to investigate the issue a bit more and/or provide a pull request?

**Comment by lucaslupo** [comment]
I initialize the view controller like this

```
self.calendarViewController = TripCalendarViewController.init(nibName: "TripCalendarViewController", bundle: nil, plan:plan)
```

```
class TripCalendarViewController: DayViewController {

 override func viewDidLoad() {
        super.viewDidLoad()
        
        dayView.autoScrollToFirstEvent = true
        dayView.delegate = self
        dayView.dataSource = self
        dayView.isUserInteractionEnabled = true
        self.reloadData()
    }
    
    init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?, plan: TrippyCommons.Plan) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        self.plan = plan
    }

 override func eventsForDate(_ date: Date) -> [EventDescriptor] {
        var events = [Event]()

        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        
        // Each dailySchedule is a day full of events
        self.plan.schedule?.dailySchedule.forEach({ dailySchedule in

// CODE TO CREATE EVENT HERE - used the exact code as the example code in the repo

```

**Comment by richardtop** [comment]
Could you please try again but without interface builder? It's not really supported with the CalendarKit.

**Comment by lucaslupo** [comment]
Sure. I initialized like this now:

```
 self.calendarViewController = TripCalendarViewController.init()
```

Same issue. By the way, it works when I scroll to the next day. It's just the first initial day that doesn't scroll to the first event

**Comment by lucaslupo** [comment]
Okay, I think I got it working now. I was still using xib for the container, which is, I was embedding the dayView.view inside another view controller in xib. Now however, I am unable to make the dayView cooperate with the rest of the UI, which is, I have a navigation bar on top and tab bar at the bottom and it seems that the dayView overlaps with them and changes the background color.


<img width="584" alt="Screen Shot 2020-04-26 at 12 41 03 PM" src="https://user-images.githubusercontent.com/62317276/80317876-3cfbf200-87bb-11ea-9622-a319d916d9fc.png">

See how the tab bar background changes
<img width="584" alt="Screen Shot 2020-04-26 at 12 40 59 PM" src="https://user-images.githubusercontent.com/62317276/80317877-3e2d1f00-87bb-11ea-90a7-22d536f9fbc4.png">

**Comment by richardtop** [comment]
Looks like some translucency issue. You can try making those bars non-translucent and see if it solves your issue.

**Comment by lucaslupo** [comment]
That worked. Thanks!
