### ISSUE TITLE
DayViewDelegate methods always Overriding non-@objc declarations from extensions

### ISSUE THREAD

**Issue by ramesh09ios** [richardtop/CalendarKit#261]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [ ] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Xcode: Version 11.3 
**issue:-**
1) Overriding non-@objc declarations from extensions is not supported
2) Value of type 'EventView' has no member 'data'
3) How to Customise EventViews

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]
extension CalendarScheduleVC {
    override func dayViewDidSelectEventView(_ eventview: EventView) {
      print("Event has been selected: \(eventview.data)")
    }

    override func dayViewDidLongPressEventView(_ eventView: EventView) {
      print("Event has been longPressed: \(eventView.data)")
    }
}

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Hi, answering your questions:

1. That's it. To fix the issue, move the methods you override back to the class declaration.
2. Issue will be solved when the 1st one is solved
3. Not currently supported, issue created to track it: #175. What kind of customizations are you interested in (please, provide a design mockup).
