### ISSUE TITLE
Setting custom initial date results in a bug when swiping right

### ISSUE THREAD

**Issue by MockinMan** [richardtop/CalendarKit#263]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
I've found the bug with setting the initial date. If the initial date is not today when swiping right will lead not to the next day, but to today one. 
I've found out that this most likely happens because in TimelineContainerController TimelineView instance is set with today.
I've experienced it in both my project (which is built on SwiftUI) and example.

##### Code I'm using with CalendarKit

```Swift

override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    move(to: myDate)
}

```

#### Result I am trying to achieve
Change the initial date when showing the calendar and get correct swiping behavior.

#### What happens
The initial date is shown as needed, but swiping right will scroll not to the NEXT date, but today one.

**Comment by richardtop** [comment]
Fixed in 0.13.11
