### ISSUE TITLE
Remove event from calendar is not possible?

### ISSUE THREAD

**Issue by lucaslupo** [richardtop/CalendarKit#265]
Hi There.

Maybe I am missing something but I can't seem to find a way to remove an event from the calendar. Any hint on how to achieve this?

Thanks!

**Comment by richardtop** [comment]
Hi, it's possible:

1. Remove the event from the `DayViewDataSource`
2. Call `DayView.reloadData()` to refresh the whole view.

Yes, you can't just "delete" an individual event, you'll have to reload the whole view, but that achieves your goal.

In the future, please ask similar programming questions on [StackOverflow with the CalendarKit tag](https://stackoverflow.com/questions/tagged/calendarkit). That would ensure a fast reply from either me or other StackOverflow members.

**Comment by lucaslupo** [comment]
Yeah that is what I tried but nothing happens on the UI when I do that... and yes, I removed the even from the datasource since if I leave and re-open the view the event is gone.
