### ISSUE TITLE
Can we send pressed location along with view reference when we click on an event

### ISSUE THREAD

**Issue by twinklenotna** [richardtop/CalendarKit#268]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
I want to know the pressed location along with the event view reference when I click on event in day view.

#### Result I am trying to achieve

override func dayView(dayView _: DayView, didTapTimelineAt time: Date,  eventView: EventView) { }

**Comment by richardtop** [comment]
Could you please elaborate on why do you need this feature? I'm planning to introduce a custom `EventView` class support, which might be difficult to add in case there is an interface as you propose.

**Comment by twinklenotna** [comment]
@richardtop I am trying to implement addEvent functionality and in the add event dialog I want to automatically set the start date of the event to `didTapTimelineAt`. Also, I am calling this addEvent functionality when we click on the specific types of events only. So it is adding an event on top of another event. That why I need the above function.

**Comment by richardtop** [comment]
Please, take a look at the example, where such functionality has been already implemented, so that you could re-use it out-of-the-box.
