### ISSUE TITLE
Week Change delegate?

### ISSUE THREAD

**Issue by BBITSDev** [richardtop/CalendarKit#269]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

#### Result I am trying to achieve

I am trying to capture Week Change event when user either swipe the top label or swipe timelineview. Is there any delegate method to detect Week change?

Thanks in advance.

**Comment by richardtop** [comment]
Please, use the following methods:

```Swift
  override func dayView(dayView: DayView, willMoveTo date: Date) {
    print("DayView = \(dayView) will move to: \(date)")
  }
  
  override func dayView(dayView: DayView, didMoveTo date: Date) {
    print("DayView = \(dayView) did move to: \(date)")
  }
```

By checking whether the new date is in a different week than the previous one, you'll be able to generate the Week Change event.

1. Store the initial date in a variable
2. Get the new date using `  override func dayView(dayView: DayView, didMoveTo date: Date) {` method
3. Compare the two dates using e.g. `NSCalendar` methods or `DateTools` library. if they're in a different week, then the week has changed.
4. Store the new date in a variable, repeat this as many times as user changes the date.

**Comment by BBITSDev** [comment]
Appreciate quick response.

**Comment by richardtop** [comment]
@BBITSDev do you have any more questions on this topic? If you've resolved this issue, please, close the ticket.
