### ISSUE TITLE
Generated Events calls only once

### ISSUE THREAD

**Issue by shaikhshoeb** [richardtop/CalendarKit#271]
There is no way to recall/referesh and call generateEventsForDate methods to referesh/reload.

suppose if we want to insert multiple event at one call events are not coming on right date it miss match the days.

**Comment by richardtop** [comment]
Please, explain problem in detail.

**Comment by shaikhshoeb** [comment]
i need to add multiple events in one shot how can i do this in this?

**Comment by richardtop** [comment]
Please, provide a sample project or sample code.

This kind of questions (not a bug report, feature request) are better to be asked on StackOverflow with the CalendarKit tag. Please ask it there.
https://stackoverflow.com/questions/tagged/calendarkit

As for adding multiple events at the same time, just do the changes to your datasource and then call `dayView.reloadData()` method to reload all events at once.
