### ISSUE TITLE
Is there any option available to select the event, and also on selection change the time and confirm the time

### ISSUE THREAD

**Issue by mlkanth7** [richardtop/CalendarKit#273]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Right now on long hold only the event can be selected directly to modify I need to just select the event. and also modify event and keep our comfortable time and then confirm

**Comment by richardtop** [comment]
Please, use the delegate methods to provide your own functionality. Do not use `CustomCalendarViewController` or `ExampleViewController` as a reference or base class.

**Comment by boominadhaprakash** [comment]
@mlkanth7 
Have you implemented that? For me also that kind of functionality required.

**Comment by richardtop** [comment]
@boominadhaprakash please ask this question on StackOverflow and make sure to add `CalendarKit` tag. https://stackoverflow.com/questions/tagged/calendarkit

People on that website are way faster answering implementation questions. Here I prefer to focus on bugs or features related to the library, or edge use-cases, not general implementation questions which are better fit for the platform such as StackOverflow
