### ISSUE TITLE
Customize EventView

### ISSUE THREAD

**Issue by BBITSDev** [richardtop/CalendarKit#275]
Can you/anyone guide me on how to customize EventView to have images or custom layout?
![image](https://user-images.githubusercontent.com/5289372/96555160-0a980100-12d5-11eb-8512-1ddb930450c9.png)

I want to achieve EventView something similar to attached image.

Thank you.

**Comment by richardtop** [comment]
Currently not supported, this feature has already been requested. Please, post your suggestion here: #175
Also, any further discussion on this topic should happen there.

**Comment by richardtop** [comment]
Also, you could just fork the CalendarKit and implement your change directly in the `EventView`
