### ISSUE TITLE
user swipe events

### ISSUE THREAD

**Issue by jaymathew** [richardtop/CalendarKit#28]
Hi, 
    Is there a way to know what dates are being shown?  user swipe callbacks?

**Comment by richardtop** [comment]
I agree, the library definitely needs such a callbacks. Let's discuss possible implementations.
What I propose is to use Apple-style events: call `will` before the action and `did` afterwards.
For example:
```Swift
func dayView(dayView: DayView, willMoveTo date: Date)
func dayView(dayView: DayView, didMoveTo  date: Date)
```
Will this implementation suit your need?
Are you going to use these callbacks to trigger data fetch or network request?
In one of my project which used [Tapku library calendar](https://github.com/devinross/tapkulibrary) I was observing requested dates in datasource method and triggering a network request if the needed date was close to current date range bounds.

Anyway, if you're OK with my example of the callbacks, I will implement them and release them soon.

**Comment by jaymathew** [comment]
I am fetching events via network. 
I really like the idea of the before and after callbacks.  
 
My only question is should the callback only give a date?  The swipes really show date ranges, maybe the callback should include a date range instead?

Thanks for the quick response

**Comment by richardtop** [comment]
Let's consider an example when CK is configured to show only 5-day week starting from Monday? Then when iterating through Fri->Mon range would be discontiguous.

I'd suggest implementing "range" logic using separate delegate object and triggering requests when needed.
Here is how I did it, it's in Objective-C, but the code is very simple:
```Objective-C
- (void) calendarDayTimelineView:(TKCalendarDayView*)calendarDay didMoveToDate:(NSDate*)date {
    if ([_currentPeriod containsDate:date interval:DTTimePeriodIntervalOpen]) {
        return;
    }
    
    NSDate *start = [date beginningOfMonth];
    NSDate *end = [date endOfMonth];
    
    _currentPeriod = [DTTimePeriod timePeriodWithStartDate:start endDate:end];
    [self performRequestWithPeriod:_currentPeriod];
}
```

What do you think about it?

**Comment by jaymathew** [comment]
looks good

**Comment by jaymathew** [comment]
New 'open' Access control in Swift 3.0 is needed instead of 'public' for these new func's. Or you get the following error:

Overriding non-open instance method outside of its defining module

**Comment by richardtop** [comment]
@jaymathew taking on it and releasing today.

**Comment by qasimsqm** [comment]
Can I disable left Right swipes?

**Comment by richardtop** [comment]
You'll need to create your own `DayView` from the CalendarKit components to achieve that functionality.
