### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by farshadtx** [richardtop/CalendarKit#284]
### New Issue Checklist

- [*] Use the latest version of CalendarKit
- [*] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [*] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

Is there any plan to support Mac Catalyst?

**Comment by richardtop** [comment]
Not at the moment, but this would be highly beneficial for the library. Feel free to implement this functionality yourself and submit a pull request.
#156

**Comment by richardtop** [comment]
Available & tested after 0.14.5
![image](https://user-images.githubusercontent.com/8013017/102712234-26655680-42c8-11eb-8ba1-5232757ede91.png)
