### ISSUE TITLE
More complex eventGap behavior

### ISSUE THREAD

**Issue by RareScrap** [richardtop/CalendarKit#288]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

We have the ability to set the gasp for EventView (via `TimelineStyle`), which is applied to the right and bottom edges of the view. However, it makes sense to gap the bottom edge only if the view is adjacent to other views. Otherwise, we distort the visual representation of the end time of the event.

In the current version of the library, access is always applied if specified (The difference in accessibility can be seen when switching views to edit mode):
<img src="https://user-images.githubusercontent.com/7997602/99252644-3e216900-284a-11eb-8377-18b1d5f3412a.gif" width="400px"/>

I suggest using bottom indentation only if the end time of one event is the start time of another (or with a slight difference).

On the gif, you can see how the bottom gap is applied only if there is another view below the view:
<img src="https://user-images.githubusercontent.com/7997602/99252036-52189b00-2849-11eb-8520-02e5429ee594.gif" width="400px"/>

It seems to me that such a feature will perfectly complement the CalendarKit. I propose to discuss this.

**Comment by richardtop** [comment]
Hi, thanks for reporting this issue. It's definitely a bug, as `eventGap` should be in effect only when the events are touching each other.
What you've described is an expected behavior, so please go ahead and implement it.

**Comment by richardtop** [comment]
Does this solve your issue?
https://github.com/richardtop/CalendarKit/pull/290
