### ISSUE TITLE
Just can't install library with CocoaPod or Swift Package

### ISSUE THREAD

**Issue by Nordin-010** [richardtop/CalendarKit#297]
### OS
MacOS Catalina (10.15.7)

### Xcode
Version 11.0 (11A420a)

### Issue
 * Can't build CalendarKit from pod
 * Can't install CalendarKit with Swift Package Manager

### Pod issue
<img width="934" alt="Screenshot 2021-01-21 at 12 01 02" src="https://user-images.githubusercontent.com/428598/105342752-0a174b00-5be1-11eb-9472-05d677cc99ee.png">

### Swift Package issue
<img width="700" alt="Screenshot 2021-01-21 at 11 59 47" src="https://user-images.githubusercontent.com/428598/105342800-18fdfd80-5be1-11eb-97ae-d86afc71fe6a.png">

How can I solve these so I can use the beautiful CalendarKit?

**Comment by richardtop** [comment]
Hi, looks like you're using an old version of Xcode. SPM requires Xcode 12+.
Please, use CocoaPods and try one of these older releases of CalendarKit:
![image](https://user-images.githubusercontent.com/8013017/105362840-0c3ed100-5c04-11eb-8f6d-da7ba5923414.png)

**Comment by Nordin-010** [comment]
Solution was upgrading from Xcode 11 to Xcode 12. Thank you @richardtop!

**Comment by richardtop** [comment]
Could you clarify, if you were using SPM or CocoaPods with Xcode 12?

**Comment by Nordin-010** [comment]
Hi @richardtop I used CocoaPods.
So after I upgraded to Xcode 12, I reinstalled CocoaPod and now everything works. By the way, I tried another pod which didn't work as well until I upgraded to Xcode 12.
I'm afraid a lot of pods are unusable now if xcode is not upgraded to version 12.

**Comment by richardtop** [comment]
OK. So it looks like the calendar kit doesn't work with Xcode 11. Could be a language version incompatibility.

Glad your issue has been resolved.
