### ISSUE TITLE
Italian localization

### ISSUE THREAD

**Issue by spiccinocchi** [richardtop/CalendarKit#303]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Missing Italian localization, it's possibile to add?

**Comment by richardtop** [comment]
Hi Simone, it's possible.
Could you please add it yourself to this folder? https://github.com/richardtop/CalendarKit/tree/master/Source/Localizations

Take a look on how the iOS calendar translates strings "12:00" and "all-day" and just add them to the **Localizable.strings**.

Looking forward to your pull request.

**Comment by spiccinocchi** [comment]
Hi,
thank you for for accepting my request. 
With CocoaPods I can istall only version 0.14.8 but you have relase version 1.0.0, Is it correct?

**Comment by richardtop** [comment]
Please, share the line you have for the CalendarKit in Podfile

**Comment by spiccinocchi** [comment]
Hi,
I solved my issue with CocoaPods and now correctly install versione 1.0.4. 
But I have notice that the All-Day string is still not localized.

**Comment by richardtop** [comment]
Could you share a screenshot of your project configuration and the screenshot of the app?
This is not reproducible in Cocoapods / SPM, for me the localization is always displayed correctly.

**Comment by richardtop** [comment]
<img width="2304" alt="Screen Shot 2021-04-27 at 19 42 17" src="https://user-images.githubusercontent.com/8013017/116280065-fb68a300-a790-11eb-8399-bf3f5845a52a.png">
<img width="1046" alt="Screen Shot 2021-04-27 at 19 42 32" src="https://user-images.githubusercontent.com/8013017/116280084-fefc2a00-a790-11eb-896a-12e01f56a6bd.png">

![Simulator Screen Shot - iPhone 12 Pro - 2021-04-27 at 19 44 12](https://user-images.githubusercontent.com/8013017/116280085-ff94c080-a790-11eb-9981-ae38ecc1dde2.png)

**Comment by spiccinocchi** [comment]
here is my project configuration and a screenshot of my app:

![Schermata 2021-04-27 alle 21 59 22](https://user-images.githubusercontent.com/42941217/116307142-3de8aa80-a7a6-11eb-9518-c3115ad40a57.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-27 at 22 07 14](https://user-images.githubusercontent.com/42941217/116307144-3e814100-a7a6-11eb-883c-e13787ba2ad2.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-27 at 22 05 59](https://user-images.githubusercontent.com/42941217/116307146-3f19d780-a7a6-11eb-92a2-9892a3892746.png)

**Comment by richardtop** [comment]
Could you please share minimal project (e.g. create a new one) which reproduces the issue? I cannot reproduce it in my setup.

**Comment by spiccinocchi** [comment]
Yes I will send you a minimal project for test.
I see in the JZAllDayCorner.swift the following line:

![Schermata 2021-04-28 alle 10 33 22](https://user-images.githubusercontent.com/42941217/116373367-8be4c900-a80d-11eb-9f06-0d9831847752.png)

where the lbltitle text is set without localization, this could be the problem or the localization is automatic?
