### ISSUE TITLE
Calendarkit having issue with user generated navigationBar  

### ISSUE THREAD

**Issue by jackspa22ow** [richardtop/CalendarKit#309]
Hello,

First of all thanks a lot for the super cool pod.
I am facing an issue with the navigation bar, So basically I am not using the system navigation bar. I have created a custom navigation bar through UIVIew in Storyboard. so when I assign a subclass as a DayViewController. My navigation bar just overlaps as you can see below the screenshot. 

![IMG_1904](https://user-images.githubusercontent.com/17780917/120640785-80319580-c490-11eb-9f46-5cd6e5f674b1.PNG)

So I wanted to hide the system-generated navigation bar as I have designed it on my way like below 

![IMG_1905](https://user-images.githubusercontent.com/17780917/120640933-ab1be980-c490-11eb-9c55-adbf9996045c.PNG)

So is there any way to fix this issue?.

Thanks in advance.

**Comment by richardtop** [comment]
Hi, please attach a sample project which reproduces the issue.

CK is not stable with storyboards / xibs, I recommend configuring your calendar view controller fully in code.

**Comment by jackspa22ow** [comment]
Please find a below-attached demo. when you run the app you'll notice that I didn't set embed in navigation controller as my out requirements are to set custom navigation bar as you can see in the storyboard.

Thanks

[TestDemo.zip](https://github.com/richardtop/CalendarKit/files/6594640/TestDemo.zip)

**Comment by richardtop** [comment]
Hi, I see few issues with your project:

CalendarKit is instantiated via Storyboard by setting the controller class to one of the ViewControllers in the Storyboard. It's not the recommended approach and it might lead to issues such as this.
Please, take a look at the [Sample App](https://github.com/richardtop/CalendarApp) and the [Video Tutorial](https://www.youtube.com/watch?v=cvF1D-F_LPw) on how to integrate your project with the CalendarKit properly.

Also, the correct way to customize navigation bar is either by following the official tutorial: [Customizing Your App’s Navigation Bar](https://developer.apple.com/documentation/uikit/uinavigationcontroller/customizing_your_app_s_navigation_bar), or by providing a custom `UINavigationBar` subclass in a custom `UINavigationController` subclass.

For the best result, I recommend embedding `DayViewController` into a `UINavigationController` and customizing it's navigation bar.

**Comment by jackspa22ow** [comment]
Let me take a review and do accordingly.

Thank you.

**Comment by gurpreetKobe** [comment]
@richardtop Kindly provide a demo project or tutorial with Storyboard as well so that we can configure it that way. My project requirements are such that I have to use a custom nav bar with a storyboard.
