### ISSUE TITLE
How to enable current month View with All 30 days ?

### ISSUE THREAD

**Issue by sw-tt-ravivora** [richardtop/CalendarKit#31]
Hi,
    I want to implement full calendar with monthView with all days of current month.

**Comment by richardtop** [comment]
Hi @sw-tt-ravivora,
this library was designed to be a configurable day view calendar.
Please, look at the other libraries to add MonthView and YearView functionality.

To sum up, CalendarKit is only DayView because there were already libraries that implemented MonthView and YearView.
