### ISSUE TITLE
How to set multiple events in CalendarKit for the same time? 

### ISSUE THREAD

**Issue by jackspa22ow** [richardtop/CalendarKit#310]
Hello
Thank you for this amazing library.

I have customized the library based on my client's requirements as he wants to show a thumbnail so I do changes accordingly.

![screenshot_1](https://user-images.githubusercontent.com/17780917/121921659-d3d89480-cd56-11eb-8ea2-88298cecc271.PNG)
 
but the issue is if there are multiple events created at the same time then it gets bunched up or cut off because of the width. as you can see below screenshot.

![screenshot_2](https://user-images.githubusercontent.com/17780917/121921891-10a48b80-cd57-11eb-9522-85a3c9d7a1fe.png)

So my client looking for UI for multiple events like below

![screenshot_3](https://user-images.githubusercontent.com/17780917/121922316-798c0380-cd57-11eb-81e4-64599f29c08e.png)

As you can see, he is looking to create space between times and add thumbnails under each other.

So can you please guide me on how can I archive this kind of UI?

**Comment by richardtop** [comment]
Hi, you'll need to fork the library and implement your own layout logic.
CK can't do this layout out of the box.

**Comment by jackspa22ow** [comment]
Okay, thanks for the suggestion.
