### ISSUE TITLE
Support 3Day/7Day same as google calendar

### ISSUE THREAD

**Issue by kalathiyanilesh1** [richardtop/CalendarKit#313]
How can i implement 3day or 7day functionality same as google calendar? is it possible with CK SDK?

like below SS
![2021_08_03T09_01_58_100Z](https://user-images.githubusercontent.com/27014642/127988782-56bab04f-aa7b-4cfb-92f5-f3c120c4a740.jpeg)

**Comment by richardtop** [comment]
Hi, this is a duplicate of the following issue: https://github.com/richardtop/CalendarKit/issues/22

This is not supported in the current form of the CalendarKit.

**Comment by xeieshan** [comment]
Switching to https://github.com/zjfjack/JZCalendarWeekView for 3-Day Calendar view

@kalathiyanilesh1 @richardtop

**Comment by ServicePal** [comment]
@xeieshan How is the JZCalendar library working our for you? Is it still maintained?
