### ISSUE TITLE
Recognize Swift Toolchain v5

### ISSUE THREAD

**Issue by spheroidic** [richardtop/CalendarKit#317]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

I am trying to include CalendarKit as a Swift Package in a project I'm working on. I have an older computer that cannot support XCode 12.5. I installed Swift Toolchain version 12.5, and I'm using it in XCode, but I still get an error message about having an old version of the Swift Toolchain:

<img width="1041" alt="Screen Shot 2021-09-13 at 9 39 33 PM" src="https://user-images.githubusercontent.com/62301101/133295372-aa42147d-9100-4c6f-93fc-224f2240082f.png">

I'm unclear on where the issue lies. Do you think this could be an issue with CalendarKit?

I have a question open on StackExchange [here](https://stackoverflow.com/questions/69171237/can-i-resolve-my-toolchain-version-error-with-this-package). I thought I'd post here as well in case anyone else has this issue.

**Comment by richardtop** [comment]
The toolchain has been updated to 5.3
