### ISSUE TITLE
Is it possible to set boder width and color for each eventView?

### ISSUE THREAD

**Issue by qubyedev** [richardtop/CalendarKit#319]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

Is it possible to set boder width and color for each eventView?

##### Code I'm using with CalendarKit

```Swift

<!-- INSERT CODE HERE -->

```

**Comment by richardtop** [comment]
No, it's not possible.
This feature has already been requested here: https://github.com/richardtop/CalendarKit/issues/175

To achieve your result, please fork the repository and adjust the `EventView` to achieve the result you'd like.
