### ISSUE TITLE
Change event view text colour

### ISSUE THREAD

**Issue by Boottexy** [richardtop/CalendarKit#32]
Hi!

Recently I started to use this library and now I need to change the label colour of all events and I can't do this. I don't know if I'm doing something wrong or what, but I can't do it.

I think this is a good aspect to think about...

**Comment by richardtop** [comment]
Hi @Boottexy,
`EventView` is a regular `UIView`, you can subclass it and do whatever you wish. For example, change color or the algorithm using which other supplementary colors are being calculated.
To change the algorithm, just override the following property:
```Swift
  public var color = UIColor() {
    didSet {
      textView.textColor = color.darkened(amount: 0.3)
      backgroundColor = UIColor(red: color.redComponent, green: color.greenComponent, blue: color.blueComponent, alpha: 0.3)
    }
  }
```
Feel free to ask more questions, if there is something missing in my answer.

**Comment by Boottexy** [comment]
Hi @richardtop!
You are totally right, it works!
I don't know but if you want you can close the issue.

Thank you very much!
