### ISSUE TITLE
Restart needed after granted calendar access to display events

### ISSUE THREAD

**Issue by niklasgrewe** [richardtop/CalendarKit#321]
Hi, i am using the latest CK Version. When i start my app the first time, i granted the permission to access my calendar. But after that, CalendarKit is not able to display events. I try to call `reloadData()` in `requestAccessToCalendar()` but with now success.

What do i need to change to display events after request access without starting the app again?

**Comment by richardtop** [comment]
Please, file this bug for the CalendarApp repository.
