### ISSUE TITLE
Support fast swipe action

### ISSUE THREAD

**Issue by kosuel** [richardtop/CalendarKit#325]
When user tries to swipe fast twice, it respond only once. I guess this is because framework only loads 3 pages at once. But many users try to swipe twice or triple to navigate different week.

**Comment by richardtop** [comment]
Looks like the fast swiping is working as expected:
I'm trying to swipe really fast, both the timeline as well as the header, and both work well. 

Which version of calendar kit are you using?

https://user-images.githubusercontent.com/8013017/144767042-62a7b710-1d04-4f39-ab95-e41f1fe03781.MOV

**Comment by kosuel** [comment]
you're right. Sorry for my mistake.
