### ISSUE TITLE
SwiftUI update?

### ISSUE THREAD

**Issue by Pamposgsk** [richardtop/CalendarKit#330]
Hi,
Do you have a plan to redesign the entire component in SwiftUI?
If yes when do you plan to do this?
Thanks 
Pampos

**Comment by richardtop** [comment]
Hi, the plan so far is to expose the whole component to SwiftUI And, maybe, expose some of the minor components (header, timeline, etc) to SwiftUI too.

What's the purpose of having to rewrite the whole library?

**Comment by richardtop** [comment]
#270 related issue

**Comment by richardtop** [comment]
It's possible to just "expose" UIKit-version of the calendar kit to SwiftUI, so that it would work as if it was a fully SwiftUI view, so there is no point in rewriting it in SwiftUI from scratch.
