### ISSUE TITLE
Event not loaded properly on View

### ISSUE THREAD

**Issue by Deepak-kumar-varshney** [richardtop/CalendarKit#331]
Hello @richardtop 

I am facing one problem in this library which is in showing in video attached below.
Problem is Event not loading properly i.e. if we have 5 event then it will show different number of count every refresh of this page

https://user-images.githubusercontent.com/65901824/154658338-50c20070-c628-4ac1-9086-d4b6719c6ab0.mp4

.

**Comment by richardtop** [comment]
Please, provide a sample code to reproduce a problem.
