### ISSUE TITLE
Event not loaded properly on View

### ISSUE THREAD

**Issue by Deepak-kumar-varshney** [richardtop/CalendarKit#332]
Hello @richardtop

I am facing one problem in this library which is in showing in sample code attached below.
Problem is Event not loading properly i.e. if we have 5 event then it will show different number of count every refresh of this page.
[Huru_Sample.zip](https://github.com/richardtop/CalendarKit/files/8108393/Huru_Sample.zip)

**Comment by richardtop** [comment]
Looks like the integration has been made incorrectly. Please use this template for your integration, not the one in the CalendarKit repository.
https://github.com/richardtop/CalendarApp
