### ISSUE TITLE
Event has no starDate or endDate

### ISSUE THREAD

**Issue by R35Master** [richardtop/CalendarKit#343]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

Hi,

I was following the latest guide on youtube to implement CK to my app. At the very beginning I had the issue "Value of type 'Event' has no member 'startDate'"

and I checked the document(EVENT.SWIFT) with option key > go to document and literally I couldnt find startDate or endDate.
<img width="635" alt="Screen Shot 2022-08-15 at 21 18 18" src="https://user-images.githubusercontent.com/109156022/184692492-4c9e649f-31e4-4e7d-a6fd-a93c414e72b4.png">

Any ideas?

##### Code I'm using with CalendarKit

```Swift

    override func eventsForDate(_ date: Date) -> [EventDescriptor] {
        
        let startDate = date
        
        var oneDayComponents = DateComponents()
        oneDayComponents.day = 1
        
        let endDate = calendar.date(byAdding: oneDayComponents, to: startDate)!
        
        let predicate = eventStore.predicateForEvents(withStart: startDate, end: endDate, calendars: nil)
        
        let eventKitEvents = eventStore.events(matching: predicate)
        
        let calenderKitEvents = eventKitEvents.map { ekEvent -> Event in
            let ckEvent = Event()
       //    ckEvent.startDate = ekEvent.startDate <<<<
       //    ckEvent.endDate = ekEvent.endDate <<<<
            ckEvent.isAllDay = ekEvent.isAllDay
            ckEvent.text = ekEvent.title
            if let eventColor = ekEvent.calendar.cgColor {
                ckEvent.color = UIColor(cgColor: eventColor)
            }
            return ckEvent
        }
        return calenderKitEvents
    }
}

```

**Comment by R35Master** [comment]
@richardtop Hi mate, could you please guide me what to do hear?

**Comment by richardtop** [comment]
Hi, the API has changed here: https://github.com/richardtop/CalendarKit/releases/tag/1.1.0

Now the API requires to set `DateInterval`: https://developer.apple.com/documentation/foundation/dateinterval

Video & discussion of the change with example: https://www.youtube.com/watch?v=rmO0TT3mQIM

Video tutorial of how to change the app (section "Refactoring the demo app"): https://youtu.be/rmO0TT3mQIM?t=1360

**Comment by R35Master** [comment]
Much appreciated @richardtop

**Comment by richardtop** [comment]
In case you don't have further questions, feel free to close this issue.
