### ISSUE TITLE
Quick question about Nav Bar Please Check Attached ss

### ISSUE THREAD

**Issue by R35Master** [richardtop/CalendarKit#344]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

Hey @richardtop first of all I wanted to thank you for quickly getting back to me yesterday. I completed the integrated and I really want to say thanks because this is the best SDK I have used for calender. Great job mate!

It works pretty fine and I will start digging deep to connect user data to my database. 

My problem is NavBar is completely black on my simulator. I checked the file under pods "UIColor+SystemColors" < this one but there is nothing that makes my nav bar complete black. Here is ss below and kindly asking your guidance;
<img width="275" alt="Screen Shot 2022-08-16 at 17 21 45" src="https://user-images.githubusercontent.com/109156022/184903544-23500e98-05e1-48d4-a79b-42986d3a5f60.png">

##### Code I'm using with CalendarKit

```Swift

<!-- INSERT CODE HERE -->
Works fine :)
```

**Comment by R35Master** [comment]
Dont mind I figured it out. So you were setting nav bar on scene delegate so I just modified it on my viewdidload.

Another question which I really couldnt find any referance; how to automatically scroll down to current time when vc is presented?

**Comment by richardtop** [comment]
1. Another question which I really couldnt find any referance; how to automatically scroll down to current time when vc is presented?

No such functionality in the library as of right now.

2. There is an open issue regarding week view, which might get developed. Regarding month view, you'll need to combine CK with some other library, as there are plenty of libraries to display the month view.

**Comment by R35Master** [comment]
Thanks a lot @richardtop , I already loved the way you build CK. Cheers!

**Comment by R35Master** [comment]
By the way, just to inform you: on models lower than iphone 8, when you click an event on the calendar there is a button toolbar for "delete" button. When you close the editing vc that toolbar stays in the bottom and if CK is integrated in an app it effects the whole app and stays there. I solved it with 
```
    override func viewWillDisappear(_ animated: Bool) {
        self.navigationController?.setToolbarHidden(true, animated: false)

    }
    override func viewWillAppear(_ animated: Bool) {
        self.navigationController?.setToolbarHidden(true, animated: false)

    }
```
this lines on my day vc. You might want to mention it if you record another youtube video. Cheers! @richardtop
