### ISSUE TITLE
Event text cutoff in timeline view for short events

### ISSUE THREAD

**Issue by DevonAllary** [richardtop/CalendarKit#347]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

Is there any way to increase the size of the hour blocks in the calendar day view or to adjust the position of the text inside the event? With short events (around 15 minutes) the event text gets cut off, even with small sized font.

![Screen Shot 2022-09-03 at 10 27 51 AM](https://user-images.githubusercontent.com/26601716/188277776-1a4d7a7f-5ed6-4d76-8869-a2185f673390.png)

##### Code I'm using with CalendarKit

I tried using the fix recommended in #236 but it's not working. 

```Swift

override func viewDidLoad() {
        super.viewDidLoad()
        title = "Calendar"
        self.dayView.autoScrollToFirstEvent = true
        var style = CalendarStyle()
        style.timeline.verticalInset = 90
        updateStyle(style)
}
```

#### Result I am trying to achieve

I'd like to either increase the size of the hour blocks or adjust the positioning of the text box inside the event so that the text doesn't get cutoff.

**Comment by richardtop** [comment]
This is in fact should work. I'll check and get back to you. Let's keep this open as a bug.

**Comment by richardtop** [comment]
Please, use `vertifalDiff` property instead:

```
  override func viewDidLoad() {
    super.viewDidLoad()
    title = "CalendarKit Demo"
    navigationController?.navigationBar.isTranslucent = false
    dayView.autoScrollToFirstEvent = true
    reloadData()
    var style = CalendarStyle()
    style.timeline.verticalDiff = 90
    updateStyle(style)
  }
```

This code works perfectly:

## Before
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-09-20 at 22 31 50](https://user-images.githubusercontent.com/8013017/191348349-6bd76744-bcb8-4716-a4d7-c1b8247839da.png)

## After
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-09-20 at 22 33 13](https://user-images.githubusercontent.com/8013017/191348375-9ba8dd1f-9b1f-4427-b853-9566bd5eb3f0.png)
