### ISSUE TITLE
Current time indicator for all dates.

### ISSUE THREAD

**Issue by littlehj** [richardtop/CalendarKit#358]
The current time indicator, which shows the current time, is only displayed if it is today. It would be a nice option for CalendarKit if it could be improved to be visible on all dates.

<img width="471" alt="CleanShot 2023-05-27 at 20 27 57@2x" src="https://github.com/richardtop/CalendarKit/assets/68091/d11a66ba-561d-4250-b0bf-676556d31991">

Thanks.

**Comment by richardtop** [comment]
Could you please elaborate on your idea? Do you propose to have an option to show current time  even for e.g. yesterday or any other day in the past/future? Which color should that indicator have?

Currently it just mimics the default Calendar app behavior, which is to show it just for "today".

**Comment by littlehj** [comment]
Currently, the time indicator is only shown if it is today, like the default Calender app.
However, I realized that it would be much more helpful to show the current time when adjusting past or future events.
I'm suggesting this because I think such a time indicator would be a good UI reference for users when adding new events or modifying existing ones.

**Comment by richardtop** [comment]
I suggest you modifying the library (forking) and then adjusting the logic of hiding that time indicator. e.g. you might change the color of the indicator for other dates than today, the relevant code is here: https://github.com/richardtop/CalendarKit/blob/master/Sources/Timeline/TimelineView.swift#L382

**Comment by littlehj** [comment]
> I suggest you modifying the library (forking) and then adjusting the logic of hiding that time indicator. e.g. you might change the color of the indicator for other dates than today, the relevant code is here: https://github.com/richardtop/CalendarKit/blob/master/Sources/Timeline/TimelineView.swift#L382

Thanks,

**Comment by richardtop** [comment]
Were you able to achieve the result you intended? Can this ticket be closed?
