### ISSUE TITLE
Navigation bar turns black

### ISSUE THREAD

**Issue by MrLaco** [richardtop/CalendarKit#361]
Hi. I'm trying to create my calendar app by your youtube tutorial. Starting from the very beginning, my navigation bar for some reason turns black. And one more thing, when I click the event and then get back, bottom part of my simulator also turns black (to be more exact the place where tab bar is usually located). Do you know what is the reason and how to fix it? By the way, you faced the same troubles but didn't show how to fix them if I'm not mistaken. Thanks =)

**Comment by richardtop** [comment]
Hi, do you still have that issue?
