### ISSUE TITLE
Horizontal scrolling for the timeline

### ISSUE THREAD

**Issue by Gerodot** [richardtop/CalendarKit#362]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description

Hello. In `DayViewController` at one and the same time can be a large number of events (can be about 100) how to make that when reaching a certain number of events appeared horizontal scrolling for the timeline?
| ![IMG_CC18D45BD04D-1](https://github.com/richardtop/CalendarKit/assets/1532819/f748890b-b34b-4816-a509-194764951c6e)| ![IMG_9D746AB12B60-1](https://github.com/richardtop/CalendarKit/assets/1532819/6cf29596-52f3-4195-bad2-1afbcdde6c7f)|
|---|---|

**Comment by richardtop** [comment]
Hi, currently horizontal scrolling is not possible to configure "out of the box", as it would interfere with the scrolling between the days.
Feel free to take a look at these issues:
https://github.com/richardtop/CalendarKit/issues/113 - I think, yours can be marked as a duplicate to this.

https://github.com/richardtop/CalendarKit/issues/357#issuecomment-1558515182 - here a workaround is listed on how to modify the layout algorithm.
