### ISSUE TITLE
Dates in the header and timeline are not synchronized

### ISSUE THREAD

**Issue by pluckq** [richardtop/CalendarKit#40]
On first load screen appear on next day, but if i scroll back it scrolls two days back, i.e. appear on 27 but if i scroll back will set on 25 (which is right if today is day back from day that appear), so problem in appearance i guess

**Comment by pluckq** [comment]
Happens in a last day of week, in days view

**Comment by richardtop** [comment]
@pluckq I cannot reproduce this issue. It may be related to the timezone. Could you comment, in which timezone you've tested this library and found the bug?

**Comment by pluckq** [comment]
UTC +5, last day of week, 2nd part of the day
appears only in header with circles, in bottom of header date is correct

**Comment by richardtop** [comment]
@pluckq interesting, seems that there is some inconsistency in how header and the other part of the calendar work with dates.

**Comment by pluckq** [comment]
Also I'm not sure about correct date in timeline scrollview, didn't test it

**Comment by richardtop** [comment]
@pluckq it's the same problem - I suspect, the dates could be calculated slightly differently - hence the inconsistency.
