### ISSUE TITLE
Perform scroll calendar horizontal header to next or prev week by button.

### ISSUE THREAD

**Issue by palozinski** [richardtop/CalendarKit#49]
Hey,

How to perform scroll horizontal calendar header to next or week by button (no gesture) ? I want do that by clicking bar button item.

**Comment by richardtop** [comment]
To scroll to the particular date (for example, any day next week), invoke a method `changeCurrentDate(to newDate: Date)` on an instance of a [DayView](https://github.com/richardtop/CalendarKit/blob/master/Source/DayView.swift).
You should be able to set an arbitrary date, be it next week or next year.
I hope, this helped you in setting up CalendarKit. If you need more help, don't hesitate to ask questions here, or if you don't have any questions, feel free to close this issue.
