### ISSUE TITLE
How to scroll to the first event

### ISSUE THREAD

**Issue by syedtariq2013** [richardtop/CalendarKit#50]
Your git comment suggested that there is a way to scroll to the first event on a day. The function scrollToFirstEvent is present but it is not clear how I can access it. Please suggest how I can handle this. Or even scroll to a specific time such as 8:00 am when I display a day view.

Are there any other examples on how to use this very useful library to implement other functions such as displaying by week or month or making an entry in a time slot.

**Comment by richardtop** [comment]
Hi @syedtariq2013, thank you for your question. I'll break down your question in a multiple parts to keep it easy to follow.

**1. Scrolling to the 1st event of the day**
Making calendar automatically scroll to the 1st event of the day is possible by setting a property `autoScrollToFirstEvent` to `true` on an instance of a [DayView](https://github.com/richardtop/CalendarKit/blob/master/Source/DayView.swift).

**2. Scrolling to the specific time**
To scroll to the specific time, invoke a method `scrollTo(hour24: Float)` on an instanceof a [DayView](https://github.com/richardtop/CalendarKit/blob/master/Source/DayView.swift). The parameter should be in 24-h format, i.e. if you would like calendar to scroll to `11:30 PM`, invoke `scrollTo(hour24: 23.5)`.
I hope, this helped you in setting up CalendarKit. If you need more help, don't hesitate to ask questions here, or if you don't have any questions, feel free to close this issue.

**Comment by syedtariq2013** [comment]
Thank you for your help

**Comment by syedtariq2013** [comment]
Hi Richard: Item 2 (Scrolling to the specific time) allowed me to meet my requirement. I called it from  my view controller which is subclassed to DayViewController using `self.dayView.scrollTo`  I tried Item 1 (scrolling to the first event) but it is not accessible from my view controller unless I inserted an open keyword in the autoScrollToFirstEvent

**Comment by richardtop** [comment]
Thanks for the feedback, I'll take a look at it in a couple of days. Until now, I fix the `open` access modifier on a `autoScrollToFirstEvent`.

**Comment by Montrazul** [comment]
Hi,

the `autoScrollTofFirstEvent` is not working always! If I initially open the `DayViewController` for the first two dates to the left and right the auto scrolling is working. But if I go further back or forward (for example 5 dates earlier) the autoscroll is not working anymore where "not working" means that the view is scrolling to the very top of the scrollview and not to the first event of that day. I tried to manually call the auto scroll in the delegate:

open func dayView(dayView: DayView, didMoveTo date: Date) {
    logger.debug("Day View did move to: \(date)");

    self.viewControllerDay.reloadData();
    self.viewControllerDay.dayView.scrollToFirstEvent();
}

But that does nothing.

**Comment by richardtop** [comment]
Fixed in #66
