### ISSUE TITLE
open event in own view controller

### ISSUE THREAD

**Issue by palozinski** [richardtop/CalendarKit#52]
How to open event n own view controller?

There is no indexPath or something like this.

`func dayViewDidSelectEventView(_ eventview: EventView)`

I want to retrieve data from realm data base in new view controller for selected Item.

**Comment by richardtop** [comment]
Hi @palozinski, 
thanks for the issue. Seems that there is really no way to easily determine which `EventView` was pressed. I'll apply fix in a few minutes.

**Comment by richardtop** [comment]
`EventView` has property `descriptor` of type `EventDescriptor` which could contain any arbitrary information.
In `Event.swift` it is possible to set any object to `userInfo` which could help identify event. Later, just fetch the `userInfo`:
```
func dayViewDidSelectEventView(_ eventView: EventView) {
    guard let indexPath = eventView.descriptor.userInfo as? IndexPath else {
        return
    }
}
```

**Comment by palozinski** [comment]
Many Thanks for improvement. 
Now, after `pod update` I have this error:

`Value of type 'EventDescriptor?' has no member 'userInfo'`

**Comment by richardtop** [comment]
Sorry, I wrote incorrect example. This should work:
```Swift
```Swift
func dayViewDidSelectEventView(_ eventView: EventView) {
    guard let descriptor = eventView.descriptor as? Event else {
        return
    }
// use descriptor.userInfo here
}
```

```

**Comment by palozinski** [comment]
Super, many thanks !
