### ISSUE TITLE
Vertical scroll [enhancement]

### ISSUE THREAD

**Issue by fanstudiouk** [richardtop/CalendarKit#56]
Hi Richards,

Thanks for sharing the CalendarKit! It's the best pod I've found so far. 

What I would suggest is to be able to enable a vertical scroll in order to get to the next day. Currently we are restricted to the horizontal one. 

Looking forward to see a detailed documentation of this amazing pod. 

Also, if you're interested in implementing some custom features please let me know.

Cheers,
Andrei

**Comment by richardtop** [comment]
Hi @fanstudiouk,
thank your for the feature request. CK was intended to be the best and fully customizable DayView and that's where I'm aiming.

Regarding your feature and Vertical Scroll: 
To add this feature, a support for vertical scroll should be added to [PagingScrollView](https://github.com/richardtop/CalendarKit/blob/master/Source/PagingScrollView.swift). 
Then, it would be possible to configure `PagingScrollView` for vertical scroll, the rest should work out of the box.

**Comment by fanstudiouk** [comment]
Hi Richard,

Thanks for your prompt reply. Will give it a shot and let you know how it goes.

Another thing that I believe it's missing or would be nice to have: when we have appointments of 10-15 minutes the height is too small and you can't see the content. It would be nice to be able to zoom-in our and adjust the timeline view height. 

Thanks!
Andrei

**Comment by richardtop** [comment]
@fanstudiouk looking forward for your results and pull requests. Feel free to ask if something is unclear.

I've moved zooming in/out to a separate task #58
