### ISSUE TITLE
Inconsistency with events displaying. 

### ISSUE THREAD

**Issue by umangshu-chouhan** [richardtop/CalendarKit#59]
Select the last date on header which doesnot have a event in his timeline. Now go to next week by scrolling week header you will see that the date on week header is selected last but the events are displaying for the next day. Also i can see same events for many days in week.

**Comment by Montrazul** [comment]
Do you mean it is like that in your own project or in the demo of `CalendarKit`?
If you talk about the demo its is obvious why there are equal events for many days in the week, since they are randomly picked from a given array of data.

**Comment by richardtop** [comment]
#9cec544a1aa5c17203c80a7ddcb1ae4566aa0bd0

**Comment by richardtop** [comment]
I cannot reproduce this bug.
Also, I've added day and month to the events in demo in [this commit](https://github.com/richardtop/CalendarKit/commit/9cec544a1aa5c17203c80a7ddcb1ae4566aa0bd0), so this issue would be easier to spot in demo.
