### ISSUE TITLE
Not able to show pending notification in Calender Day view

### ISSUE THREAD

**Issue by ratnesh-iOSdev** [richardtop/CalendarKit#60]
I was setting local notification, and later I tried to set those pendingNotificationArray as dayModel DataSource, but its crashing in library. Any clue?

**Comment by richardtop** [comment]
Hi Ratnesh, could you please provide source code showing how you are using the library and a stack trace of the crash?

**Comment by richardtop** [comment]
@ratnesh-iOSdev I'm closing this issue, feel free to reopen if you would like to continue discussion and there is still something unclear.
