### ISSUE TITLE
Overlapping Events Not Being Detected

### ISSUE THREAD

**Issue by jurysch** [richardtop/CalendarKit#61]
I've seen numerous instances of events not being properly detected as overlapping, which causes one event to draw atop another given than their x-offset is incorrectly calculated.

In TimelineView.recalculateEventLayout(), the currently-operated-on event is only checked for overlap with the array's most recently added event, not the previous events in the array that could potentially be overlaps.

Is this potentially related to issue #43 ?

**Comment by richardtop** [comment]
Hi @jurysch, 
you're absolutely correct, it's a know issue. Thanks for reporting. I will get back to it in a couple of weeks.

**Comment by richardtop** [comment]
@jurysch, I've improved algorithm in PR #67, does this algorithm resolves your issue?
