### ISSUE TITLE
Crash when selecting year in the future 2020

### ISSUE THREAD

**Issue by bithavoc** [richardtop/CalendarKit#71]
> Xcode Version 8.3 (8E162)

When running the example with `pod try CalendarKit` I found that the calendar crashes with `fatal error: Index out of range` when you select any year in the future.

See at `DayHeaderView.scrollviewDidScrollToViewAtIndex`
<img width="1140" alt="screen shot 2017-07-04 at 5 58 00 pm" src="https://user-images.githubusercontent.com/219289/27844094-5722db56-60e2-11e7-836b-1a80cd28ff8c.png">

**Comment by richardtop** [comment]
Hi @bithavoc,
thanks for reporting this issue.

I'd like to ask you for more insights, more precisely, what actions caused the bug?
For example, scrolling header forward, or trying to set date using `DayViewState`?

**Comment by bithavoc** [comment]
@richardtop this is a pretty impressive component, thank you for sharing.

It will crash after clicking in "Done" as shown in the following screen:

![screen shot 2017-07-04 at 6 09 00 pm](https://user-images.githubusercontent.com/219289/27844198-ee107c52-60e3-11e7-8baf-38234a8e8fa5.png)

It's triggered by:
```
func doneButtonDidTap() {
    delegate?.datePicker(controller: self, didSelect: date)
  }
```

**Comment by richardtop** [comment]
@bithavoc thanks, I appreciate!
That is known bug and related to #55.
I will fix it in a couple of days.
