### ISSUE TITLE
Add support for editing events by drag&drop

### ISSUE THREAD

**Issue by adavan2107** [richardtop/CalendarKit#72]
Thanks for the awesome library. I have integrated the same in my project, i need to drag and drop event view to the next page like ical.please advice 

thanks in advance

**Comment by richardtop** [comment]
Hi @adavan2107, 
currently, there is no support for editing events: moving between pages or changing the duration.

**Comment by NadeemHakim** [comment]
When do you think this could be available

**Comment by richardtop** [comment]
I am not working on this issue right now and not planning on adding this feature in the near future.
However, you're welcome with a pull request if you'd like to introduce this feature.

**Comment by daveleenew** [comment]
hope drag support  thanks

**Comment by LOG-TAG** [comment]
![image](https://user-images.githubusercontent.com/1190344/56137467-8e6f7f80-5fb2-11e9-9b85-0b02b14e258d.png)

**Comment by richardtop** [comment]
Implemented in v 8.0
