### ISSUE TITLE
After creating event in eventsForDate ->Crash Report

### ISSUE THREAD

**Issue by mukulm24** [richardtop/CalendarKit#75]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -hash not defined for the UIColor <UIPlaceholderColor: 0x1700343e0>; need to first convert colorspace.'

**Comment by mukulm24** [comment]
event.color needs to be specified before adding an event.

**Comment by richardtop** [comment]
Need to set default color for event, I'll mark this issue as open.
