### ISSUE TITLE
How can we change time interval to half hour from 1 hour??

### ISSUE THREAD

**Issue by mukulm24** [richardtop/CalendarKit#76]
I wish to change the time interval on Day view controller from 1 hour to 1/2 hour.

**Comment by richardtop** [comment]
It's not yet possible, but is related to #58

**Comment by mukulm24** [comment]
Work around is to increase the height of the cell from 45 to 150 or something. This makes me adding multiple events in one hour

**Comment by richardtop** [comment]
@mukulm24 could you please explain more in detail?
Currently CK does not support changing the scale of the timeline.

**Comment by mukulm24** [comment]
In TimelineView.swift 
change to

 var verticalDiff: CGFloat = 160

this increases the width to show more events within an hour.

**Comment by richardtop** [comment]
@mukulm24 I see, this solution will make timeline bigger, but still, there would be no possibility to zoom in and out like in the default iOS calendar. However, it may be a good workaround, if zoomable timeline is not needed.

**Comment by mukulm24** [comment]
To add slots for half hour and quarter, we can use the following code in TimelineView.swift

override public func draw(_ rect: CGRect) {
    super.draw(rect)

    var hourToRemoveIndex = -1

    if isToday {
      let minute = currentTime.minute
      if minute > 39 {
        hourToRemoveIndex = currentTime.hour + 1
      } else if minute < 21 {
        hourToRemoveIndex = currentTime.hour
      }
    }

    let style = NSParagraphStyle.default.mutableCopy() as! NSMutableParagraphStyle
    style.lineBreakMode = .byWordWrapping
    style.alignment = .right

    let attributes = [NSParagraphStyleAttributeName: style,
                      NSForegroundColorAttributeName: self.style.timeColor,
                      NSFontAttributeName: timeFont] as [String : Any]

    for (i, time) in times.enumerated() {
      let iFloat = CGFloat(i)
      let context = UIGraphicsGetCurrentContext()
      context!.interpolationQuality = .none
      context?.saveGState()
      context?.setStrokeColor(self.style.lineColor.cgColor)
      context?.setLineWidth(onePixel)
      context?.translateBy(x: 0, y: 0.5)
      let x: CGFloat = 53
      let y = verticalInset + iFloat * verticalDiff
      context?.beginPath()
      context?.move(to: CGPoint(x: x, y: y))
      context?.addLine(to: CGPoint(x: (bounds).width, y: y))
      context?.strokePath()
      context?.restoreGState()

      if i == hourToRemoveIndex { continue }

      let timeRect = CGRect(x: 2, y: iFloat * verticalDiff + verticalInset - 7,
                            width: leftInset - 8, height: fontSize + 2)

      let timeString = NSString(string: time)
    
      // line to be added for 30 min interval
      let subLineContext = UIGraphicsGetCurrentContext()
      subLineContext!.interpolationQuality = .none
      subLineContext?.saveGState()
      subLineContext?.setStrokeColor(self.style.halfHourLineColor.cgColor)
      subLineContext?.setLineWidth(1)
      subLineContext?.translateBy(x: 0, y: 0.5)
      let halfHourX: CGFloat = 53
      let halfHourY = (verticalInset + iFloat * verticalDiff) + (verticalDiff/2)
      subLineContext?.beginPath()
      subLineContext?.move(to: CGPoint(x: halfHourX, y: halfHourY))
      subLineContext?.addLine(to: CGPoint(x: (bounds).width, y: halfHourY))
      subLineContext?.strokePath()

      //lines to be added for 15 min interval
      subLineContext?.setStrokeColor(self.style.quarterLineColor.cgColor)
      let firstQuarterY = (verticalInset + iFloat * verticalDiff) + (verticalDiff/4)
      subLineContext?.beginPath()
      subLineContext?.move(to: CGPoint(x: halfHourX, y: firstQuarterY))
      subLineContext?.addLine(to: CGPoint(x: (bounds).width, y: firstQuarterY))
      subLineContext?.strokePath()
       
      subLineContext?.setStrokeColor(self.style.quarterLineColor.cgColor)
      let secondQuarterY = (verticalInset + iFloat * verticalDiff) + ((verticalDiff/4) + (verticalDiff / 2))
      subLineContext?.beginPath()
      subLineContext?.move(to: CGPoint(x: halfHourX, y: secondQuarterY))
      subLineContext?.addLine(to: CGPoint(x: (bounds).width, y: secondQuarterY))
      subLineContext?.strokePath()

      //add half hour time string
      let halfHourTimeRect = CGRect(x: 2, y: (iFloat * verticalDiff + verticalInset - 7) + (verticalDiff/2),
                              width: leftInset - 8, height: fontSize + 2)
        
      var halfHourTimeString = NSString()
      
      //To be changed in a better quality code with proper time references. This is a work around
      if is24hClock {
        halfHourTimeString = NSString(string: time.replacingOccurrences(of: ":00", with: ":30"))
      }else {
         halfHourTimeString = (time == "Noon") ? NSString(string: "12:30") : NSString(string: time.replacingOccurrences(of: " AM", with: ":30").replacingOccurrences(of: " PM", with: ":30"))
      }
        
      timeString.draw(in: timeRect, withAttributes: attributes)
        
      halfHourTimeString.draw(in: halfHourTimeRect, withAttributes: attributes)
   
    }
  }

**Comment by richardtop** [comment]
@mukulm24 thanks for the code samples, I'll definitely take a look at it when working on #58 
May I close this issue, as it has been resolved?
