### ISSUE TITLE
Crash when move(to:) is called

### ISSUE THREAD

**Issue by harshag** [richardtop/CalendarKit#77]
Hi @richardtop 
Thanks for creating CalendarKit, it has saved several hours of our development effort.

We have a requirement to navigate to next week on tap of a button, using move(to:) we are able to do this, however, strangely we encounter a crash only when we select the first day of the week and then move to previous week. For all other scenarios it works fine.

The way we are doing is,
```
    func moveDayView(withTimeChunk time : TimeInterval,from currentDate : Date) {
        let dateAfterSwipe = currentDate.addingTimeInterval(time)
        dayView.state = DayViewState(date: currentDate)
        dayView.state?.move(to: dateAfterSwipe)
        dayView(dayView: dayView, willMoveTo: dateAfterSwipe)
    }
```

I have attached screenshot where it crashes soon after the move happens
![movetocrash](https://user-images.githubusercontent.com/1763746/28671126-2d74b8d2-72f9-11e7-8488-1969a95fd3e5.png)

**Comment by richardtop** [comment]
Hi @harshag, it's a known bug and it's related to #71, #55.
