### ISSUE TITLE
Not able to run pod for 0.1.21 the latest version

### ISSUE THREAD

**Issue by iOSUser110** [richardtop/CalendarKit#80]
I want to change the current date ,
and date change issue is resolved in your latest library .
But unable to install pod with current branch , or by putting the version 0.1.21

please reply

**Comment by richardtop** [comment]
Hi @iOSUser110,
Most likely, your local Cocoapods repository hasn't been updated.
try running `pod update` and see if it resolves the issue.

I tried to install CalendarKit to an empty project and everything worked fine:
![image](https://user-images.githubusercontent.com/8013017/29003857-424276e8-7ac7-11e7-9dfb-bad5979358a6.png)
