### ISSUE TITLE
Ability to customize Event View on Timeline Calendar

### ISSUE THREAD

**Issue by gavinpquinn** [richardtop/CalendarKit#83]
I'd like to be able to insert images, bold fonts, colors, etc.

Perhaps just using attributedText instead of plain text would be nice?

**Comment by richardtop** [comment]
Hi @gavinpquinn, 
I will add this feature in a couple of days.

**Comment by gavinpquinn** [comment]
Hi @richardtop any luck with this item?

**Comment by richardtop** [comment]
Hi @gavinpquinn, it is fixed in PR #88, feel free to reopen this issue or comment if you need other changes.
Thanks for patience!
