### ISSUE TITLE
How to create a event by clicking on the time slot 

### ISSUE THREAD

**Issue by vgyan** [richardtop/CalendarKit#87]
Couldn't able to find If this feature already exists ? 
Can you please point out on How to ?

**Comment by richardtop** [comment]
Hi Viscenario,
There is no such functionality in the library.
To implement it, you need to use the delegate method:
```Swift
func dayViewDidLongPressTimelineAtHour(_ hour: Int)
```
This method will be called when user does `long-press` event on the timeline. In your app you could handle it and present UI for creating new event with the specified timeslot, which you can get as a `hour` parameter.

Or, maybe you would like to have a delegate method responding to `tap` event instead. If so, there is no such functionality, but I can add it by your request.

**Comment by vgyan** [comment]
Thank you .. Will check that!

**Comment by richardtop** [comment]
@vgyan I'm closing this issue as you don't have any further questions. If you'd like to ask about something else, feel free to reopen it or create a new one.
