### ISSUE TITLE
Can`t find CalendarKit

### ISSUE THREAD

**Issue by Zane6w** [richardtop/CalendarKit#9]
Can`t find CalendarKit in CocoaPods, and download the Zip can`t opened.

**Comment by richardtop** [comment]
@Zane6w Could you provide more details?
Try `pod repo update`, then `pod try CalendarKit`

or, in podfile:
```Ruby
pod 'CalendarKit'
pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools.git', :branch => 'swift'
```
and then `pod update`

**Comment by Zane6w** [comment]
ok, i`ll try, thanks

**Comment by richardtop** [comment]
@Zane6w is your issue resolved by now?

**Comment by Zane6w** [comment]
@richardtop  is resolved, thank you.
