### ISSUE TITLE
Xcode 9 and Swift 4 Migration - Help

### ISSUE THREAD

**Issue by vgyan** [richardtop/CalendarKit#91]
![screen shot 2017-09-25 at 7 46 42 am](https://user-images.githubusercontent.com/1185806/30808959-bd6672f0-a1c5-11e7-92cc-ba4f247f511b.png)

**Comment by richardtop** [comment]
The latest version of the pod should work fine.
Are you on `0.2.0`?

If not, you can update to the latest version with:
`pod update`

**Comment by vgyan** [comment]
Thanks.. That fixed the issue, Of course I had to build the framework on Xcode 9 and add to my project to make it work.
