### ISSUE TITLE
How to add start date and end date ?

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [richardtop/CalendarKit#92]
@richardtop  Thanks! I want add date start and end date. ?
`info.append("\(datePeriod.beginning!.format(with: "08:00")) - \(datePeriod.end!.format(with: "08:30"))")`
This is not working. its taken current date. help me

**Comment by richardtop** [comment]
It seems to me, there is an error in your code in format string.
Referring to the [example](https://github.com/richardtop/CalendarKit#usage), you could format start date and end date strings as shown here:
```Swift
info.append("\(datePeriod.beginning!.format(with: "HH:mm")) - \(datePeriod.end!.format(with: "HH:mm"))")
```
Did it help you?

**Comment by IOSDeveloperProgrammer** [comment]
@richardtop Thanks for the response! 
`frmdt": "04-Sep-2017",
            "todt": "10-Sep-2017",
            "strdt": "2017-09-03T18:30:00.000Z",
            "endt": "2017-09-09T18:30:00.000Z",
            "frmtm": "08:45",
            "totm": "09:30",
            "caldate": "04-Sep-2017 - 10-Sep-2017",
            "caltime": "08:45 - 09:30",
this im getting array from server. i need to show on calendar. i stuck  to implementing your code. can youbplease let me know . some example code . how can i implement and acheive it. please guide me.

**Comment by richardtop** [comment]
In your example there are separate entries for dates and for texts to be presented to the user. So, we need to use only text to configure the UI, this should work.
However, I noticed, that the server returns incorrect dates (18:30 for both the start and the end):
```
"strdt": "2017-09-03T18:30:00.000Z",
"endt": "2017-09-09T18:30:00.000Z",
```
I'd recommend fixing that at first.

This is an example on how to use the strings provided by the server:
```Swift
info.append(caldate)
info.append(caltime)
```

**Comment by IOSDeveloperProgrammer** [comment]
@richardtop  thanks ! I'll try and let you know.

**Comment by vgyan** [comment]
May be date formatting issue.. Try "yyyy MM dd HH:mm:ss.SSS" format..

**Comment by IOSDeveloperProgrammer** [comment]
@richardtop @vgyan Sorry for late reply. it's nothing happen in calendar. (not working )

Usually i am getting response of every month as like below
` "rowid": "1",
            "classid": "id",
            "classname": "I ",
            "frmdt": "04-Sep-2017",
            "todt": "10-Sep-2017",
            "strdt": "2017-09-03T18:30:00.000Z",
            "endt": "2017-09-09T18:30:00.000Z",
            "frmtm": "08:00",
            "totm": "08:45",
            "caldate": "04-Sep-2017 - 10-Sep-2017",
            "caltime": "08:00 - 08:45",
            "sun": "Weekly Off",
            "mon": "subj",
            "tue": "subj",
            "wed": "subj",
            "thu": "subj",
            "fri": "subj",
            "sat": "Weekly Off"`

Please help me out of this issue . Thanks

**Comment by maheshiosdeveloper** [comment]
How to select the date in default it is taking the current date

**Comment by IOSDeveloperProgrammer** [comment]
@maheshiosdeveloper  How to create time period. I'm trying to create one event. but #101 please help me i'm stuck
