### ISSUE TITLE
Feature Request: Add support for custom hour height

### ISSUE THREAD

**Issue by jameswwwebster** [richardtop/CalendarKit#93]
Events that are short can often have their text clipped. Adding support for a custom height to be used for the hours could resolve this in the short term. Long term I see this expanding to support pinch-zoom.

This is a feature that I plan to implement myself and submit as a pull request, however it would be good if there could be some feedback about potential pitfalls or suggested implementation before any work is done.

**Comment by richardtop** [comment]
Hi,
I suggest setting a property, e.g. in `TimelineStyle` and implementing an update code. There should be no need in any changes of the drawing code in `TimelineView`.
So, at first, adding these two properties to the `TimelineStyle` should make custom calendar scale possible:
![image](https://user-images.githubusercontent.com/8013017/30967514-3467cf38-a465-11e7-86a4-f58b37766317.png)

**Comment by jameswwwebster** [comment]
Yeah I'd experimented by changing these some of the properties directly. I'll work with these.

**Comment by jSunnari** [comment]
Hi, any updates how to use this?

**Comment by jdtzmn** [comment]
@richardtop Any updates?
