### ISSUE TITLE
Feature Request: Allow access to created event views so that they can be customised.

### ISSUE THREAD

**Issue by jameswwwebster** [richardtop/CalendarKit#96]
The specific case I have in mind is that I would like to be able to add a small warning image to events that are in a different timezone. This could be solved very specifically by adding an image view for example, however allowing access to the view itself allows for more general customisation.

A drawback however is that parts that really should remain immutable (like bounds) would be exposed.

This is a feature that I plan to implement myself and submit as a pull request, however it would be good if there could be some feedback about potential pitfalls or suggested implementation before any work is done.

**Comment by richardtop** [comment]
There are a couple of points you might want to check before starting this feature:
1. There is already a support for `attributedText` - maybe, this is a solution to a problem. [Pull Request](https://github.com/richardtop/CalendarKit/pull/88)
2. If this is not enough, I'd recommend adding a protocol for a generic `EventView` and the possibility of registering any view conforming to that protocol in `Timeline`.

**Comment by richardtop** [comment]
Implemented in the latest release of the CalendarKit
