### ISSUE TITLE
Master branch isn't in sync with pod spec.

### ISSUE THREAD

**Issue by jameswwwebster** [richardtop/CalendarKit#99]
The podspec references 0.2.0. No newer tag has been created for the latest pull request or documentation changes.

**Comment by richardtop** [comment]
I've pushed all the latest changes to the CocoaPods `specs` repo now.
Release URL: https://github.com/richardtop/CalendarKit/releases/tag/0.2.1

**Comment by jameswwwebster** [comment]
Thanks for the quick response!
